### ISSUE TITLE
Roadmap to improve TTL delete and TTL move functionality

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#10128]
Current implementation of TTL delete and TTL move is not very intuitive or user friendly.

## Usability ##

1. [ ] OPTIMIZE FINAL should do everything and get table to the correct state in regards to TTL
2. [x] TTL operation is triggered once per partition with 'merge_with_ttl_timeout' that is default to 24 hours, or during background part merge. This is too slow if user has a lot of partitions that have crossed the TTL trigger point. TTL should process all affected partitions.
3. [x] There is no way to force TTL manually without part merge. Need to add a new SYSTEM or ALTER command to allow manual control: OPTIMIZE TABLE TTL.
4. [x] When TTL expression is added to the table the old partitions are not being deleted/moved but user would expect this. Currently MATERIALIZE TTL is required. Since it is consistent with ALTER TABLE behaviour in general, it could be an an extension of ALTER TABLE syntax: ALTER TABLE MODIFY TTL [MATERIALIZE] https://github.com/ClickHouse/ClickHouse/pull/11042.
5. [x] When mutation is performed on the columns that are used in the TTL expression, no changes are done to pre-computed TTLs. MATERIALIZE TTL is required. This should be fixed.
6. [ ] A large number of background TTL operations using the same disk with many threads can actually hurt performance due to disk I/O bottleneck. Need a separate resource management. So we need a control over:
   * Number of threads. 
   * Priority (default -- lower than queries and merges). 
   * TTLs at the beginning of the policy should be executed first (usually first volume is the smallest).
7. [x] Need to a way to stop all moves immediately including currently executing and restart them at some later time: SYSTEM START|STOP TTL

## Introspection ##

1. [x] Extend system.parts with the information about TTLs as a set of arrays: min/max per part, last_ttl, next_ttl (https://github.com/ClickHouse/ClickHouse/pull/10591).
   * As a side effect it allows to query parts have crossed the TTL trigger point and are scheduled for delete/move.
   * The system command that triggers the TTL operation may just reset next_ttl
2. [x] Add an introspection table similar to system.merges/mutations in order to monitor active deletes 
and moves.
3. [x] TTL expression should be exposed in system.tables (for moves done in https://github.com/ClickHouse/ClickHouse/pull/10591)
4. [ ] TTL expression should be exposed in system.tables

**Comment by CurtizJ** [comment]
> There is no way to force TTL manually without part merge. Need to add a new SYSTEM or ALTER command to allow manual control: OPTIMIZE TABLE TTL.

```ALTER MATERIALIZE TTL [IN PARTITION]```?

> When mutation is performed on the columns that are used in the TTL expression, no changes are done to pre-computed TTLs. MATERIALIZE TTL is required. This should be fixed

It's not correct. See test 01070_mutations_with_dependencies.

**Comment by alex-zaitsev** [comment]
> > There is no way to force TTL manually without part merge. Need to add a new SYSTEM or ALTER command to allow manual control: OPTIMIZE TABLE TTL.
> 
> `ALTER MATERIALIZE TTL [IN PARTITION]`? This query also recomputes and prunes parts with existing ttl metadata.

It only re-computes the TTLs but does not trigger the TTL move/delete. That's a point.

**Comment by filimonov** [comment]
> It's not correct. See test 01070_mutations_with_dependencies.

:+1: So that is done :) #8775

**Comment by alexey-milovidov** [comment]
First need to get done with small issues in the list: https://github.com/ClickHouse/ClickHouse/pulls/excitoon

**Comment by filimonov** [comment]
- [ ] TTL expression should be exposed in system.tables

**Comment by filimonov** [comment]
#5491

**Comment by filimonov** [comment]
#11042

**Comment by alex-zaitsev** [comment]
#10591

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/11576

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/13252 remove creaned parts

**Comment by CurtizJ** [comment]
#16895 remove cleaned parts, second version

**Comment by filimonov** [comment]
- [ ] ATTACH PARTITION from another table shoud do materialize ttl

**Comment by vmihailenco** [comment]
>When TTL expression is added to the table the old partitions are not being deleted/moved but user would expect this. Currently MATERIALIZE TTL is required. Since it is consistent with ALTER TABLE behaviour in general, it could be an an extension of ALTER TABLE syntax: ALTER TABLE MODIFY TTL [MATERIALIZE] #11042.

So I've added TTL expression today that was supposed to move 1% of parts (or even nothing - it looks like it does not matter). What happened instead:
1. I've got lots of mutations for all the parts in the table (and that table is big)
2. those mutations used all free disk space (which is only re-claimed after 8 minutes)
3. those mutations degraded performance

I guess it is because of this improvement. I don't find it intuitive or user friendly. Old behavior was at least harmless.

**Comment by filimonov** [comment]
> I guess it is because of this improvement. I don't find it intuitive or user friendly. Old behavior was at least harmless.

Materialize ttl should not be heavy, and should not take lot of disk space - it just initialize the metadata required for ttl execution. Need more details of what was happening.

**Comment by vmihailenco** [comment]
I have a table that already had `TTL time + INTERVAL 1 MONTH DELETE` and `ttl_only_drop_parts = 1` set when table was created.

Table is partitioned slightly unusually `PARTITION BY intDiv(bitShiftRight(id, 33), 86400)`, which in the end partitions data the same as `toStartOfDay(time)` (Snowflake-like ids). I was told that this should not be a problem for TTL + DELETE. Is it a problem for TTL + MOVE?

I executed roughly

```sql
ALTER table MODIFY TTL
    time + INTERVAL 29 DAY TO 's3',
    time + INTERVAL 1 MONTH DELETE
```

I've chosen 29 days to make sure that if something bad happens it will happen only to 1-2 days of data and will be relatively fast.

What I observed was:
- lots of merges in system.merges with is_mutation=1
- mutation in system.mutations with lots of names in `parts_to_do_names` (now the column is empty)
- increased disk usage roughly the size of the table (but it is hard to be sure)

It seemed to be the same the 2nd time I've run that query.

---

I've tried to ask this on Telegram but got no definitive response:
- Does `time + INTERVAL 29 DAY TO 's3'` moves the whole partition (ttl_only_drop_parts = 1)? Or it tries to clean up what it can from existing parts?
- If I rely only on storage policy (and remove TTL+MOVE) to move the data to s3 when first volume fills up - which parts CH will move to S3? the oldest? the largest? random?

**Comment by filimonov** [comment]
> What I observed was:
>   lots of merges in system.merges with is_mutation=1
>   mutation in system.mutations with lots of names in parts_to_do_names (now the column is empty)
>   increased disk usage roughly the size of the table (but it is hard to be sure)

I've checked it and It seems something is not working as I expected.
Sounds like a bug/issue for me: https://github.com/ClickHouse/ClickHouse/issues/20338

> Does time + INTERVAL 29 DAY TO 's3' moves the whole partition (ttl_only_drop_parts = 1)? Or it tries to clean up what it can from existing parts?

Whole. It doesn't try to split the part.

> If I rely only on storage policy (and remove TTL+MOVE) to move the data to s3 when first volume fills up - which parts CH will move to S3? the oldest? the largest? random?

AFAIR the largest.

**Comment by filimonov** [comment]
Forbid TTL for tables with old syntax: #20282 #17904 #19064

**Comment by alexey-milovidov** [comment]
> Add an introspection table similar to system.merges/mutations in order to monitor active deletes
and moves.

Done with the `merge_type` column in `system.merges`.

**Comment by alexey-milovidov** [comment]
> Need to a way to stop all moves immediately including currently executing and restart them at some later time: SYSTEM START|STOP TTL

Done with the introduction of `SYSTEM STOP TTL MERGES`.

**Comment by SaltTan** [comment]
TTL expression for columns should be exposed in system.columns

**Comment by azat** [comment]
> Add an introspection table similar to system.merges/mutations in order to monitor active deletes

- #42660
