### ISSUE TITLE
Small tasks on SQL compatibility

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10540]
- [x] 1. Implement `UNION DISTINCT`. For implementation just add Distinct transform after union.
Add syntax `UNION` without ALL or DISTINCT and setting `union_default_mode` (similar to `join_default_strictness`) with values: empty string, ALL, DISTINCT. When set to empty string, UNION without ALL or DISTINCT will throw an exception. When set to ALL or DISTINCT, the query will be rewritten in AST level.

- [x] 2. Implement NULL and NOT NULL modifiers after data type in table definition and in all places where data type can be parsed (e.g. CAST function/expression). If the type is not Nullable and if NULL is specified, it will be treated as Nullable; if NOT NULL is specified, it's noop. E.g. `INT NULL` is the same as `Nullable(INT)`. If the type is Nullable and NULL or NOT NULL modifiers are specified, exception will be thrown. Add a setting `data_type_default_nullable` with values 0 and 1. If the value is 1, then data types without explicit modifier in table definition will be Nullable.

- [x] 3. Implement a setting `rollup_use_null` with values 0 and 1. When value is 1 and there is GROUP BY ... WITH ROLLUP or WITH CUBE, then RollupTransform and CubeTransform will treat GROUP BY keys as Nullable and emit Nullable columns. #38642

- [x] 4. Implement positional specification for ORDER BY, GROUP BY and LIMIT BY. E.g. ORDER BY 1, 2. This does not correspond to SQL standard but improves compatibility with other DBMS. It should be controlled by setting `enable_positional_arguments`. #2592 

- [x] 5. Implement a setting `aggregate_functions_nullable_result`. When this setting is enabled, aggregate functions will be rewritten with `-OrNull` modifier. #16123

- [x] 6. `count` and `countDistinct` (among with all `uniq` variants) from Nullable arguments should return non-Nullable result. For implementation, add a property to `IAggregateFunction`.

- [x] 7. Add support for multi-word expressions for data types, e.g. CHAR VARYING, DOUBLE PRECISION. Most of these complex expressions will simply map to existing data types.

- [x] 8. Support numeric parameters in VARCHAR, VARBINARY, INT... data types (e.g. `VARCHAR(255)`) and ignore them completely.

- [x] 9. `CAST` operator should accept not only exact data types but also data type modifiers #7119.

- [x] 10. Provide NUMERIC as a synonim to DECIMAL; provide many other similar symonims. Example: https://dev.mysql.com/doc/refman/8.0/en/other-vendor-data-types.html

**Comment by ucasFL** [comment]
> * [ ]  1. Implement `UNION DISTINCT`. For implementation just add Distinct transform after union.
>   Add syntax `UNION` without ALL or DISTINCT and setting `union_default_mode` (similar to `join_default_strictness`) with values: empty string, ALL, DISTINCT. When set to empty string, UNION without ALL or DISTINCT will throw an exception. When set to ALL or DISTINCT, the query will be rewritten in AST level.

Hi, I want to do this! @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@ucasFL Great, it's yours :+1:

**Comment by ucasFL** [comment]
Hi, I have some question about this task, do we support such as `SELECT ``` UNION SELECT ... UNION ALL/UNION DISTINCT SELECT ...`, and if support, we should compute in what order? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Subqueries can be grouped by parentheses. The logical order is defined by these parentheses.
If there are no parentheses, we should assume that UNION operation is left-associative.

E.g. if we have a query:

```
SELECT 1
UNION ALL
SELECT 1
UNION 
SELECT 2
UNION ALL
SELECT 2
```

it is the same as

```
((((SELECT 1)
UNION ALL
SELECT 1)
UNION 
SELECT 2)
UNION ALL
SELECT 2)
```

Then we can do an optimization: if there is UNION DISTINCT, all previous UNION DISTINCT can be rewritten to UNION ALL (as it does not change the result).

MySQL: http://sqlfiddle.com/#!9/0a28f18/521
PostgreSQL: http://sqlfiddle.com/#!17/0a28f/345

**Comment by alexey-milovidov** [comment]
@novikd is working on `rollup_use_null`

**Comment by alexey-milovidov** [comment]
I checked that item №9 was formulated slightly incorrectly

> CAST operator should accept not only exact data types but also data type modifiers

Actually, it does not take type modifiers in MySQL.
And `cast_keep_nullable` is sufficient for compatibility.

Now all items are done!
