### ISSUE TITLE
Roadmap to improve functionality of Live View tables

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#10581]
Roadmap to improve functionality of Live View tables.

# Tasks

## Easy
- [ ] Add support for `TO table` clause when creating live views.
  https://github.com/ClickHouse/ClickHouse/pull/10578
- [ ] Add support for `TO [TABLE] FUNCTION table_function` clause when creating live views.
  https://github.com/ClickHouse/ClickHouse/pull/10568
- [ ] Add support for auto-refresh using `WITH AUTO REFRESH` syntax.
  https://github.com/ClickHouse/ClickHouse/pull/14822
- [ ] Add support for keeping live view table always in sync even if there are no active `WATCH` queries using the `WITH ALWAYS ON` syntax.
- [ ] Add support for using the `WATCH` query inside `SELECT`. For example, `SELECT * FROM WATCH lv`.
- [ ] Add support for selecting specific columns inside the `WATCH` query. For example, change syntax to support only `WATCH  col1, col2 FROM lv` and `WATCH * FROM lv`. Alternatively, without breaking current syntax add support for `WATCH SELECT col1, col2 FROM lv` and `WATCH SELECT * FROM lv`.

## Medium
- [ ] Add support for `LIVE CHANNEL` in order to combine output of multiple live views into one channel. This is needed for web application that have a dashboard using multiple live views. Browsers, do not support large number of always open connections. Reference https://github.com/ClickHouse/ClickHouse/pull/3925.
- [ ] Add support for `DISTRIBUTED LIVE VIEW` table engine and `SELECT` query over it.
- [ ] Add support for using live views with replicated tables by
      storing mergeable blocks inside the most appropriate `ReplicatedMergeTree` table. 

## Hard
- [ ] Add support for merging of mergeable blocks so that we don't have to re-execute the query after N number of inserts.
- [ ] Add support for reducing mergeable blocks size if the data there is no longer needed. For example, when a stored query has a subquery with a `LIMIT` clause.

## Super Hard
- [ ] Add support for generic pub/sub interface:
     - [ ] for regular tables subscribe for INSERT blocks
     - [ ] for replicated tables subscribe for INSERT or replicated blocks
     - [ ] for Kafka subscribe for blocks that are consumed
     - [ ] for system tables subscribe for changes
- [ ] Add support for `WATCH` query in the `DISTRIBUTED LIVE VIEW` table engine.
