### ISSUE TITLE
clickhouse-local usability improvements

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11123]
A loose list of ideas.

The main principle is that clickhouse-local should be your go-to tool for ad hoc manipulation of tabular data in well-known formats.

Also see the comp-local label: https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aissue+is%3Aopen+label%3Acomp-local

- [x] Determine File columns from the file header for TSVWithNamesAndTypes. Goodbye to endlessly writing out the table structure, a real imporvement to the quality of life. #24756

- [x] Parse TSVWithNamesAndTypes in parallel. Yes, it doesn't work now, because of the header. #30178

- [ ] Support a function for output to multiple files, with path given by an input column. This might be useful if you have to split the data by some key to feed it to an external tool. For now it can be emulated by prefixing all rows with the key and then splitting the file by this prefix using grep -- e.g. see what I do for flamegraphs in perf tests: https://github.com/ClickHouse/ClickHouse/blob/432648ca1ee3a5055bc6cd91bc35dbd88457b952/docker/test/performance-comparison/compare.sh#L603 . #30274

- [x] Load a query from file. Now I just cat hundreds of lines into `--query` parameter and then endlessly scroll through `set -x` output. -- we now have the `--queries-file` option.

**Comment by filimonov** [comment]
> Determine File columns from the file header for TSVWithNamesAndTypes. Goodbye to endlessly writing out the table structure, a real imporvement to the quality of life.

Extra options: 
- take all columns as strings
- determinie minimal type of the column
- auto name columns as col1,..., colN

That will also allow to read CSV / CSVWithNames (which are most common)

**Comment by alexey-milovidov** [comment]
See #14450

**Comment by alexey-milovidov** [comment]
> Support a function for output to multiple files, with path given by an input column. This might be useful if you have to split the data by some key to feed it to an external tool.

It is also solved by: `INSERT INTO FUNCTION file('out{_partition_id}.csv') PARTITION BY column`
Although partition with SELECT INTO OUTFILE is still to be implemented.

Let's close this umbrella task
