### ISSUE TITLE
20.5 release checklist release

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#11288]
- [x] Cannot compare DB::Array with std::__1::basic_string #11286
- [x] visitParamExtractRaw #11254
- [x] Rename function extractAllGroups to extractAllGroupsVertical #11554
- [x] Wait for the patch from Albert with the fixes to top sort optimization #11291
- [x] Remove "system_tables_lazy_load" option #11307
- [x] Rename setting `optimize_arithmetic_operations_in_agr_func` to `optimize_arithmetic_operations_in_aggregate_functions` or different name.
- [x] Potential segfault report #11490
- [x] Pipeline stuck #11636
- [x] Hyperscan libunwind crash wrong flags. #11725
- [x] https://github.com/ClickHouse/ClickHouse/issues/11741
- [x] disable or fix broken optimization #10047

**Comment by filimonov** [comment]
i'm also adding more settings for Kafka and adjusting some defaults (ETA ~ 1d), It would be great to pick those to 20.5 too.

**Comment by alexey-milovidov** [comment]
@filimonov Yes, 20.5 branch does not exist right now, it will be created after this checklist will be done.

**Comment by filimonov** [comment]
Kafka changes can be reviewed/merged: #11388

**Comment by Enmk** [comment]
`extractAllGroupsVertical` + `extractAllGroupsHorizontal`: https://github.com/ClickHouse/ClickHouse/pull/11554

**Comment by filimonov** [comment]
More Kafka improvements: #11599

**Comment by alexey-milovidov** [comment]
+ Undiagnosed error with secondary index from one of Yandex Cloud clients (from private chat).

**Comment by alexey-milovidov** [comment]
I have removed `- [ ] Illegal column Const(UInt32) of argument of function IPv4CIDRToRange #11245` from the checklist.

**Comment by alexey-milovidov** [comment]
#11806 must be included in 20.5.
