### ISSUE TITLE
CI Fest #6

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11815]
- [ ] Build check fails sporadically without any diagnostics @alesapin 
- [x] too many simultaneous queries in "alter settings race" test: https://clickhouse-test-reports.s3.yandex.net/10379/e1fa39d801e21a80bcf63ddffebb1fb8b119d3c0/functional_stateless_tests_(ubsan).html
- [x] test_always_fetch_merged/test.py::test_replica_always_download https://clickhouse-test-reports.s3.yandex.net/10632/5bfadc6e90621951b8612eae1999fe35a95d0144/integration_tests_(release).html and https://clickhouse-test-reports.s3.yandex.net/10712/d98bc1175c986871200c9817b7a363461319f9fc/integration_tests_(release).html and https://clickhouse-test-reports.s3.yandex.net/11550/bdcf1170ced2f334d9a273815b9ac8064f4046ba/integration_tests_(release).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/11648/6467302ad32b4dd6205542675d54fa89944d0ff1/integration_tests_(release).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/11688/9ad00187e3286fa3c0c04f720981181b842dbbfd/integration_tests_(release).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/0/ff0262626ab08919909d967b2859ee107656e659/integration_tests_(release).html and https://clickhouse-test-reports.s3.yandex.net/0/ac93f2795c2890011516eddd5ae9d7442f3049c4/integration_tests_(release).html
- [x] TSan stress test sometimes killed by OOM: https://sandbox.yandex-team.ru/task/670887196/hardware
- [x] MemorySanitizer: use-of-uninitialized-value in collectSymbolsFromELF [ClickHouse Unit Tests Msan Clang-10 for PR #11711](https://clickhouse-test-reports.s3.yandex.net/11711/660ed26389e1b75583e2805393eb4713960fa74f/unit_tests_msan_clang-10.html#fail1)
- [x] create table engine Log: _LIBCPP_ASSERT '!empty()' https://github.com/ClickHouse/ClickHouse/issues/11926
- [x] Clear password in command line, race condition: https://clickhouse-test-reports.s3.yandex.net/11858/18ec373369d13a1d22f8c3faa680e49d9e2d1f8c/functional_stateless_tests_(thread)/test_run.txt.out.log Fix: #11872
- [x] segfault on `SELECT max(multiply())` https://clickhouse-test-reports.s3.yandex.net/11214/e42c07954dc91429d2e3d02a00079695bd6e63d9/stress_test_(thread).html
- [ ] Docker prepare failed: https://sandbox.yandex-team.ru/task/708147271/view @alesapin 
- [ ] test_dictionaries_all_layouts_and_sources/test.py::test_simple_dictionaries[3]. Incorrect result with thread sanitizer. https://clickhouse-test-reports.s3.yandex.net/0/4a73fe7477d52d806d71d2b2d57a8a2ca6e679e9/integration_tests_(thread).html. @alesapin and https://clickhouse-test-reports.s3.yandex.net/9516/2cda3c962ceb1c420919e3a187b89ef746421e9c/integration_tests_(asan).html#fail1
- [ ] [Logical error](https://github.com/ClickHouse/ClickHouse/blob/497df3086f9f7212655b301c841477735f9e6442/src/Storages/StorageReplicatedMergeTree.cpp#L1154), can be reproduced with `00993_system_parts_race_condition_drop_zookeeper` and https://clickhouse-test-reports.s3.yandex.net/0/90b5e5d2f9edbcd4f01bd596ec919a32368fd716/functional_stateless_tests_(debug).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/12314/260bcb9d795e2ea5607fd6a50481b4c2698c0249/functional_stateless_tests_(debug).html#fail1
- [ ] test_zookeeper_config/test.py::test_secure_connection broken with tsan [link](https://clickhouse-test-reports.s3.yandex.net/0/1a067484c8602d4de060f73235c570f0584bceec/integration_tests_(thread).html) thread sanitizer [trace](https://gist.github.com/alesapin/65ece433d6f077a406d60dfcb609d1e0)
- [ ] logical error in ReplicatedMergeTreeQueue, 01035_concurrent_move_partition_from_table_zookeeper: https://clickhouse-test-reports.s3.yandex.net/9813/da7fa82ee0746fe70906476cd5f474f6a600ebbc/functional_stateless_tests_(debug).html#fail1
- [ ] topK functional test: https://clickhouse-test-reports.s3.yandex.net/0/4bb3381bc997f29bfbb412e75290c8036c843660/functional_stateless_tests_(release).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/12278/e1543c18414e566fe7cbaaa3342e061357dfbf51/functional_stateless_tests_(release,_databaseatomic)/test_run.txt.out.log
- [ ] `No route to host` -- test_mysql_protocol - https://clickhouse-test-reports.s3.yandex.net/11163/ec894e7cb3e0e3f9f7c880b00d44ee3b83e028ad/integration_tests_(asan).html#fail1
- [ ] live view tests https://clickhouse-test-reports.s3.yandex.net/9813/05eed28b775e0029e6ccbe4655411e34681c1b67/functional_stateless_tests_(release,_polymorphic_parts_enabled).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/9515/f6b69949589b83df1d7db24c5ae9d305a9fceb3b/functional_stateless_tests_(address).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/9515/f6b69949589b83df1d7db24c5ae9d305a9fceb3b/functional_stateless_tests_(memory).html#fail1 and https://clickhouse-test-reports.s3.yandex.net/12055/b5fbd62a6f3c8cc426c82b77702d19e936315059/functional_stateless_tests_(release,_databaseatomic).html#fail1
- [ ] `00652_replicated_mutations_zookeeper.stdout`  https://clickhouse-test-reports.s3.yandex.net/0/d2be6c036b3b2f4bec8de985a9c620f9ae2cd28d/functional_stateless_tests_(release).html
- [ ] `test_distributed_respect_user_timeouts/test.py::test_reconnect[configs-default-node2-remote]` +
`[configs-default-node1-remote]` + `[configs_secure-default-node2-remote]`
  https://clickhouse-test-reports.s3.yandex.net/0/ff0262626ab08919909d967b2859ee107656e659/integration_tests_(thread).html https://clickhouse-test-reports.s3.yandex.net/0/1a3a19391c144c3aed96d29db8bb47f5b0b899d7/integration_tests_(thread).html
- [x] unitialized memory in `FunctionExtractAllGroups` https://clickhouse-test-reports.s3.yandex.net/11745/4c0879ae300c40ca0d1aa20e5f4e4856fb96c401/stress_test_(memory).html#fail1 and race condition https://clickhouse-test-reports.s3.yandex.net/11920/29a9d4187f569cc781cffbc712c1a3ddb3fcfb82/stress_test_(thread).html#fail1.
- [ ] ThreadPool.ExceptionFromSchedule https://clickhouse-test-reports.s3.yandex.net/11718/03f39fe1f434d7541ab7f2cd4e9149304fda7b19/unit_tests_relwithdebuginfo_gcc-9.html#fail1
- [ ] 01064_incremental_streaming_from_2_src_with_feedback https://clickhouse-test-reports.s3.yandex.net/0/561d4b5b0108b300746d9a03978d7dfa75d58a36/functional_stateless_tests_(release,_databaseatomic).html
- [ ] use-of-uninitialized-value DB::parseIPv6 https://clickhouse-test-reports.s3.yandex.net/0/e460d7c2bd58b379cc68a2a2e144305af36f9c02/stress_test_(memory).html
- [x] #11885 std::bad_typeid https://clickhouse-test-reports.s3.yandex.net/0/171753e7eb6aea1120e9a9fc1b0c2823fe43fefd/functional_stateless_tests_(debug).html
- [ ] `00738_lock_for_inner_table` https://clickhouse-test-reports.s3.yandex.net/12045/987e64acfe789689b8710add5d04371b8f21b604/functional_stateless_tests_(debug).html#fail1
- [ ] `01318_long_failing_mutation_zookeeper` https://clickhouse-test-reports.s3.yandex.net/0/6f2d9999be75efdab1d4753620d6943592e674d0/functional_stateless_tests_(unbundled).html
- [ ] `01280_ttl_where_group_by ` https://clickhouse-test-reports.s3.yandex.net/0/ad53ef2c14da180fd56efa6439307e4650052a3d/functional_stateless_tests_(release,_databaseatomic).html
- [x] `01267_alter_default_key_columns` https://clickhouse-test-reports.s3.yandex.net/0/9cab822718a1855240a1828ba8cd5ca15579c161/functional_stateless_tests_(unbundled).html fix https://github.com/ClickHouse/ClickHouse/pull/12088
- [ ] Yandex Synchronization Check sometimes show bogus results @exprmntr
- [x] 00975_indices_mutation_replicated_zookeeper.sh
https://clickhouse-test-reports.s3.yandex.net/0/dd907b2ee98af1920c6a990fcc5fcb669098cdba/functional_stateless_tests_(debug).html#fail1 Fix #12336
- [x] Race condition in ReplicatedMergeTreeQueue: https://clickhouse-test-reports.s3.yandex.net/12313/e17995cb75316417326b1f882409a571cbdf91c2/functional_stateless_tests_(thread)/stderr.log Fix: #12315
- [x] 00721_force_by_identical_result_after_merge_zookeeper. Most likely fixed in #12157
- [ ] multiSearch, MSan: https://clickhouse-test-reports.s3.yandex.net/12292/eaa13d81769af71d6c620881e7064ff47285c9aa/stress_test_(memory).html#fail1 (something related to Hyperscan?)

**Comment by alexey-milovidov** [comment]
materialize index: https://clickhouse-test-reports.s3.yandex.net/11831/4b7d253c8ab5225862e3ac4d443198e4d93072b6/functional_stateless_tests_(release,_polymorphic_parts_enabled)/test_run.txt.out.log

**Comment by alexey-milovidov** [comment]
#11835
#11834

**Comment by alexey-milovidov** [comment]
Clear password in command line, race condition: https://clickhouse-test-reports.s3.yandex.net/11858/18ec373369d13a1d22f8c3faa680e49d9e2d1f8c/functional_stateless_tests_(thread)/test_run.txt.out.log

**Comment by alexey-milovidov** [comment]
#11872

**Comment by alexey-milovidov** [comment]
01079_parallel_alter_detach_table_zookeeper timeout https://clickhouse-test-reports.s3.yandex.net/0/d147cd646a1e6cc41d42f92d57f016a5c49d04de/functional_stateless_tests_(thread).html#fail1

**Comment by alesapin** [comment]
> 01079_parallel_alter_detach_table_zookeeper timeout https://clickhouse-test-reports.s3.yandex.net/0/d147cd646a1e6cc41d42f92d57f016a5c49d04de/functional_stateless_tests_(thread).html#fail1

Fix in master https://github.com/ClickHouse/ClickHouse/commit/ca552d63940a3652da72c24e65e4aedd8793546a. Table was not attached and we just wait almost all 10 minutes on sync replica.

**Comment by alexey-milovidov** [comment]
> TSan stress test sometimes killed by OOM: https://sandbox.yandex-team.ru/task/670887196/hardware

It was an issue in "Sandbox" infrastructure - looks like their servers were limited to 64 GiB memory for some period of time.

**Comment by alexey-milovidov** [comment]
shutdown_table_after_detach:

https://clickhouse-test-reports.s3.yandex.net/11901/53997f23e6cd34ec97c0e03d23a26184fdc5a633/functional_stateless_tests_(memory)/test_run.txt.out.log

**Comment by alexey-milovidov** [comment]
01133_max_result_rows:

https://clickhouse-test-reports.s3.yandex.net/11908/5a7e921135d27de93cf25479fd46a0eb7527ba3b/functional_stateless_tests_(release,_polymorphic_parts_enabled).html#fail1

**Comment by alexey-milovidov** [comment]
test_adaptive_granularity/test.py::test_version_update_two_nodes

https://clickhouse-test-reports.s3.yandex.net/11974/2a1937625b0abf0ed8244c90284af15b57e8814e/integration_tests_(asan).html

**Comment by alesapin** [comment]
01193_metadata_loading
https://clickhouse-test-reports.s3.yandex.net/12052/cf306c5be13e6cf128e656086f8e0319e84c4de3/functional_stateless_tests_(thread).html#fail1

**Comment by alesapin** [comment]
> test_adaptive_granularity/test.py::test_version_update_two_nodes
> 
> https://clickhouse-test-reports.s3.yandex.net/11974/2a1937625b0abf0ed8244c90284af15b57e8814e/integration_tests_(asan).html

Resolved in docker images.

**Comment by alesapin** [comment]
`00943_materialize_index`
https://clickhouse-test-reports.s3.yandex.net/12067/a541683efa81cd07d2bf6c27cdb65c5a9cc6b82b/functional_stateless_tests_(unbundled).html#fail1

**Comment by alexey-milovidov** [comment]
Split build smoke test:
https://github.com/ClickHouse/ClickHouse/pull/12134#issuecomment-653829989

Need to add retries for all docker run / docker pull, etc.

**Comment by alexey-milovidov** [comment]
Integration test:

test_distributed_ddl/test.py::test_rename[configs_secure]

https://clickhouse-test-reports.s3.yandex.net/0/5d2013f2240f450e25323a482e3a02312dc92849/integration_tests_(thread).html#fail1

**Comment by alexey-milovidov** [comment]
Build check still fails sporadically: https://clickhouse-builds.s3.yandex.net/0/f08ff9010eb8bd8628cf009c5d6543502432ed41/clickhouse_build_check/build_log_716952857_1594003292.txt

**Comment by alexey-milovidov** [comment]
00721_force_by_identical_result_after_merge_zookeeper: not fixed.
Obvious race condition: mutation vs. OPTIMIZE.

**Comment by alexey-milovidov** [comment]
Cannot clone submodules:

https://clickhouse-test-reports.s3.yandex.net/0/9c829e3046cae0711ca822998d1a6b3e59b54edb/clone_repo/submodules_init.err.log

Need to add retries.

**Comment by alexey-milovidov** [comment]
multiSearch, MSan:
https://clickhouse-test-reports.s3.yandex.net/12292/eaa13d81769af71d6c620881e7064ff47285c9aa/stress_test_(memory).html#fail1
(something related to Hyperscan?)

**Comment by alexey-milovidov** [comment]
Race condition in ReplicatedMergeTreeQueue: https://clickhouse-test-reports.s3.yandex.net/12313/e17995cb75316417326b1f882409a571cbdf91c2/functional_stateless_tests_(thread)/stderr.log

**Comment by alexey-milovidov** [comment]
Fix: #12315

**Comment by alexey-milovidov** [comment]
00975_indices_mutation_replicated_zookeeper.sh - fix #12336

**Comment by BohuTANG** [comment]
Functional stateless tests (debug):
https://clickhouse-test-reports.s3.yandex.net/12314/260bcb9d795e2ea5607fd6a50481b4c2698c0249/functional_stateless_tests_(debug).html#fail1

**Comment by alexey-milovidov** [comment]
It is already mentioned as
> Logical error, can be reproduced with 00993_system_parts_race_condition_drop_zookeeper and https://clickhouse-test-reports.s3.yandex.net/0/90b5e5d2f9edbcd4f01bd596ec919a32368fd716/functional_stateless_tests_(debug).html#fail1

**Comment by alexey-milovidov** [comment]
Sporadic build failure: https://clickhouse-builds.s3.yandex.net/12378/a4b35a8a6fe524793e36a09d234ee8a42437f3ca/clickhouse_build_check/build_log_720579080_1594364683.txt

**Comment by alexey-milovidov** [comment]
Connection reset by peer while downloading test data from s3: #12411
Need to add retries.

**Comment by BohuTANG** [comment]
> It is already mentioned as
> 
> > Logical error, can be reproduced with 00993_system_parts_race_condition_drop_zookeeper and https://clickhouse-test-reports.s3.yandex.net/0/90b5e5d2f9edbcd4f01bd596ec919a32368fd716/functional_stateless_tests_(debug).html#fail1

Aha, maybe we should add a failure-collector-robot to detect unintended failure from the *run.txt.out.log and submit to this issue

**Comment by alexey-milovidov** [comment]
My collegue @qoega has prepared a dashboard for failed tests. This dashboard is going to become public.

**Comment by alexey-milovidov** [comment]
Sporadic failure in build:

> Error response from daemon: Get https://registry-1.docker.io/v2/yandex/clickhouse-deb-builder/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Ayandex%2Fclickhouse-deb-builder%3Apull&service=registry.docker.io: EOF
2020-07-12 21:59:05,774 Cannot pull image yandex/clickhouse-deb-builder:latest

**Comment by alexey-milovidov** [comment]
Hyperscan and async unwinding: https://clickhouse-test-reports.s3.yandex.net/12440/e8a3f0abb3e3169f0ade88bc2edd076ea4a0cff1/functional_stateful_tests_(release).html#fail1

**Comment by alexey-milovidov** [comment]
00933_test_fix_extra_seek_on_compressed_cache

https://clickhouse-test-reports.s3.yandex.net/12503/cd7ed94a085d1c810bff7a84abca1a1786e7e2a2/functional_stateless_tests_(release,_databaseatomic)/test_run.txt.out.log

Maybe another read can happen during select query (system log)?

**Comment by alexey-milovidov** [comment]
00981_topK_topKWeighted_long:

https://clickhouse-test-reports.s3.yandex.net/12278/e1543c18414e566fe7cbaaa3342e061357dfbf51/functional_stateless_tests_(release,_databaseatomic)/test_run.txt.out.log

Reproduced second time since 2020-05-26 02:29:39.

**Comment by alexey-milovidov** [comment]
Continued in https://github.com/ClickHouse/ClickHouse/issues/12508

**Comment by alexey-milovidov** [comment]
@alesapin 

> test_adaptive_granularity/test.py::test_version_update_two_nodes

>    https://clickhouse-test-reports.s3.yandex.net/11974/2a1937625b0abf0ed8244c90284af15b57e8814e/integration_tests_(asan).html

> Resolved in docker images.

It's not fixed, see #12508
