### ISSUE TITLE
20.6 release checklist

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#12081]
- [x] Segfault in StorageMerge #12054
- [x] Segfault in MergeTreeBaseSelectProcessor #12053 
- [x] Fix function if with FixedString arguments of different sizes #12021 #11362
- [x] Segmentation Fault with *StateResample combinator #12044
- [x] The list https://github.com/ClickHouse/ClickHouse/labels/prio-major must be empty.

**Comment by filimonov** [comment]
Let's also clean those bugs: https://github.com/ClickHouse/ClickHouse/labels/prio-major

**Comment by flipper86** [comment]
is it possible to have a JSONEachRow parser for deep json structure in the next release? e.g. able to parse nested json with following format {header: {key1: value, key2: value}}? :)

**Comment by alexey-milovidov** [comment]
@flipper86 We have `JSONAsString` format in version 20.5.
This format reads JSONs are a table with single String field containing whole JSON object.
You can use this format to parse JSON as String and then use JSONExtract... functions to extract fields from nested data.

**Comment by alexey-milovidov** [comment]
About this task - it is a checklist for significant issues that must be fixed before the next release, not for features.
New features come to whatever release that is going to be next after the feature is merged to master.

**Comment by alexey-milovidov** [comment]
We consolidate issues according to the following criteria:
- regressions (something works worse or with unintended broken compatibility with previous versions);
- major issues (e.g. reproducible crashes).

**Comment by alexey-milovidov** [comment]
20.6 has become prestable. If no more issues will be found, it will be released to stable this week.

**Comment by calebeaires** [comment]
@alexey-milovidov  is there some way to test it? I have found one bug os alter table deletion that it is a problem on of my server, but not in another.

I have tried to update like this, but the release does not have the **next** version 

`sudo apt install clickhouse-server=20.6`

**Comment by den-crane** [comment]
@calebeaires 

https://repo.yandex.ru/clickhouse/deb/prestable/main/

cat /etc/apt/sources.list.d/clickhouse.list
deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
deb http://repo.yandex.ru/clickhouse/deb/testing/ main/
deb http://repo.yandex.ru/clickhouse/deb/prestable/ main/

apt-get update

apt-get install clickhouse-server=20.6.1.4066  clickhouse-client=20.6.1.4066  clickhouse-common-static=20.6.1.4066

**Comment by alexey-milovidov** [comment]
Version 20.6 is released as stable.

The delay of 25 days was due to extended testing in Yandex.Metrica and Yandex Banner System that has to be performed manually and has revealed some additional issues that were fixed.
