### ISSUE TITLE
20.11 release checklist

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#16367]
Add here everything that should be fixed before version 20.11.

- [x] Rename welchTTest to match the style https://github.com/ClickHouse/ClickHouse/pull/16407
- [x] Server prints repeated messages `<Trace> DatabaseCatalog: Not found any suitable tables to drop, still have 1 tables in drop queue` @tavplubix #16584
- [x] The code of studentTTest and welchTTest is total garbage. Almost every line of code is awful trash. If they are in version 20.10, we should not even mention them in the changelog. #16593

**Comment by alexey-milovidov** [comment]
The only unresolved issue: sometimes server can create cut metadata files - only when run with UBSan in stress test in Sandbox and only when the test that creates and drops 10 000 tables is present.

**Comment by alexey-milovidov** [comment]
We have investigated this issue: #16772
