### ISSUE TITLE
20.12 release checklist

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#16870]
A list of issues that are blocking the 20.12 release.

* [x] DB::AggregateFunctionTimeSeriesGroupSum<false>::serialize segfault #16862
* [x] Null pointer in InDepthNodeVisitor<DB::SelectAggregateFunctionOfGroupByKeysMatcher #16803
* [ ] 20.9.4 Segmentation fault during a merge #16841 (cannot reproduce)

**Comment by filimonov** [comment]
check also the list of [prio-major](https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aopen+is%3Aissue+label%3Aprio-major) issues.
