### ISSUE TITLE
Prometheus endpoint improvements

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#20200]
- [x] https://github.com/ClickHouse/ClickHouse/issues/10571 Prometheus metrics contain illegal character sequence, ensure correct type is reported (some metrics are floats, see https://github.com/ClickHouse/clickhouse_exporter/issues/44 )
- [ ] https://github.com/ClickHouse/ClickHouse/issues/10043 Export sql query results to prometheus (and may be to system.asynchronious_metrics) ? 
- [x] https://github.com/ClickHouse/ClickHouse/issues/19570 system.parts (and other system tables): fill only requested columns 
- [ ] custom metric naming schemas (compat layer for https://github.com/ClickHouse/clickhouse_exporter https://github.com/Altinity/clickhouse-operator/blob/a112229168babd83abfc8eb2f2bef9dee19e94e6/pkg/apis/metrics/exporter.go ) 
- [ ] add system.errors
- [ ] configurable constant labels like: type='development',source='clickhouse' 
- [ ] create some 'standrard' set of dashboard / alerts.

**Comment by filimonov** [comment]
expose following as counters:
- Parts 
- InactiveParts 
- ActiveParts 
- SkippingIndexesGranulasScanned
- SkippingIndexesGranulasSkipped

**Comment by filimonov** [comment]
#24564

**Comment by filimonov** [comment]
> * Parts
> 
> * InactiveParts
> 
> * ActiveParts

Covered here https://github.com/ClickHouse/ClickHouse/commit/e238fd64acabf3c1adaaf05340a563d837887040

**Comment by alexey-milovidov** [comment]
Implemented all the features by #36206
