### ISSUE TITLE
Tasks on cross-compilation and platforms support

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#24371]
- [x] Add cross compilation for linux-ppc64le: #9589, see also [the list](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+author%3Amastertheknife);
- [x] Add cross compilation for darwin-aarch64: #20245;
- [x] Enable tests under QEMU for linux-aarch64 on our linux-amd64 servers: #15174 (most preparation is already done, definitely will work; the server will run under QEMU and the client will run natively);
- [ ] Don't allow distributed queries across servers with different CPU architecture: #22581;
- [ ] Add cross compilation for illumos-amd64, see #23746 and #24144 (it depends if `lld` can generate binaries for Illumos or if some other cross-linker exists);
- [ ] Try Darling: #15609 (there is high chance that it will fail but we have to try);

Further steps:
- [x] Publish deb, rpm, tgz and Docker images for linux-aarch64 builds in releases;
- [x] Put headers and blobs (libc-related `.so`, `crt*.o`) for every toolchain in git submodules. Leave only required blobs (it is around 10 MBs in size - ok for git); #29974
- [x] Make default linux-amd64 build to use sysroot similar to cross-compiling for hermetic/reproducible builds; #30011
- [x] Allow to disable all the remaining usages of `dlopen` (loading of CatBoost) and make static build with `Musl`; (we will later introduce our own dynamic loader for simple use cases to avoid usage of `dlopen`) #30248

**Comment by traceon** [comment]
Please, please, abandon the idea of cross compilations...

**Comment by alexey-milovidov** [comment]
No one complained about Illumos builds in a year, so the task of cross-compilation for Illumos is no longer relevant.

**Comment by Felixoid** [comment]
the last step to make packages available on https://packages.clickhouse.com is in #38580

**Comment by alexey-milovidov** [comment]
Most of the items are implemented, closing.
