### ISSUE TITLE
Proposed changes for "clickhouse install"

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#25514]
Currently, there are several issues/shortcomings with `clickhouse install`:

- [x] 1. (fixed in #30295) If a custom prefix path is specified via `--prefix /some/path` (and only that path is customized), then at least some of other paths are still rooted in `/`, the following error message confirms that:
```
$ ./programs/clickhouse install --prefix /home/traceon/Development/prefix/
Copying ClickHouse binary to /usr/bin/clickhouse.new
Install must be run as root: sudo ./clickhouse install
Code: 76, e.displayText() = DB::ErrnoException: Cannot open file /usr/bin/clickhouse.new, errno: 13, strerror: Permission denied (version 21.7.1.1)
```

- [x] 2. (fixed in #30295) If some of the customized paths does not exist, it would make sense to create all required nested directories automatically, as if `mkdir -p /custom/path` was executed. Currently, it causes an error:
```
$ ./programs/clickhouse install --prefix /home/traceon/Development/prefix --binary-path /home/traceon/Development/prefix/usr/bin --config-path /home/traceon/Development/prefix/etc/clickhouse-server --log-path /home/traceon/Development/prefix/var/log/clickhouse-server --data-path /home/traceon/Development/prefix/var/lib/clickhouse --pid-path /home/traceon/Development/prefix/var/run/clickhouse-server --user traceon --group traceon
std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in space: No such file or directory [/home/traceon/Development/prefix/usr/bin]
Cannot print extra info for Poco::Exception (version 21.7.1.1)

Run with sudo.
```

- [ ] 3. `Run with sudo.` from the above, and in general... This should be optional, a recommendation with a clear description of why it is recommended, and what won't be done automatically if `clickhouse install` is executed on behalf of unprivileged user, and how all those extra steps can be performed manually later. E.g., here it would be nice to have a sample command for adding capabilities in the output message:

```
Setting capabilities for clickhouse binary. This is optional.
unable to set CAP_SETFCAP effective capability: Operation not permitted
Cannot set 'net_admin' or 'ipc_lock' or 'sys_nice' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually.
```

- [ ] 4. `clickhouse install` copies `clickhouse` binary to `.../usr/bin/`, but for developers who want to use a binary that they build from sources initially and then modify and rebuild it, it makes sense to support a hidden flag, like `--dev`, that will cause a symlink `clickhouse` to be created in `.../usr/bin/` that would point to the original binary instead of copying it, so that when it is rebuilt, the new version of the binary is picked up automatically, when accessed from the "installed" paths.

- [ ] 5. `clickhouse install` creates symlinks in `.../usr/bin/` like `clickhouse-server`, `clickhouse-client`, etc., that point to the absolute path of `clickhouse`, i.e., to `.../usr/bin/clickhouse`. It is better to change the path to relative, i.e., to just `clickhouse`, so that when and if the path of the prefix is changed (due to moving, or remounting under some other path), at least the symlinks remain valid.

- [x] 6. (fixed in #30295) `--prefix`, `--config-path`, etc., don't affect the default paths in the created/copied `config.xml`, which is very misleading.

- [ ] 7. With a customized paths, esp. the custom config path, it would be useful to somehow "hardcode" or provide some bootstrapping method for the `clickhouse` executable installed in a custom path, to use that custom config path by default, so that there is no need to provide `--config /custom/config/path/config.xml` each time, to actually execute ClickHouse correctly with all the custom "installed" paths.

- [x] 8. It is interactive. It asks at least for a password for the default user. It would be nice to have an option that will allow to run `clickhouse install` unattended, from within a script.

- [ ] 9. (partially worked around in #30295 by defaulting and supporting the current user/group only) It calls some commands in attempt to create user/group. Those commands are Linux-specific. It doesn't work In macOS, for example.

- [x] 10. (implemented in #30295, the empty user/group will avoid manipulating ownership) It would be nice to be able to have some fallback behavior for `--user` and `--group` to take effective uid, etc., instead of the default `clickhouse:clickhouse`.

**Comment by alexey-milovidov** [comment]
Ok. Also let's think how to write tests for clickhouse install.
We can use integration tests or maybe `sh` tests with `chroot` would suffice.

**Comment by loyd** [comment]
Now `install --prefix` is unusable.

Want to check the latest build:
```
curl https://clickhouse.com/ | sh
./clickhouse install --prefix local --user loyd --group loyd
```

Ok, `local` is created with everything, let's start the server:
```
./clickhouse start --prefix local --user loyd
 chown -R loyd: 'local/var/run/clickhouse-server/'
Will run local/usr/bin/clickhouse-server --config-file local/etc/clickhouse-server/config.xml --pid-file local/var/run/clickhouse-server/clickhouse-server.pid --daemon
/bin/sh: line 1: local/usr/bin/clickhouse-server: No such file or directory
Code: 302. DB::Exception: Child process was exited with return code 127. (CHILD_WAS_NOT_EXITED_NORMALLY) (version 21.13.1.2209)
```

It's (5) problem, ok, fix
```
rm local/usr/bin/clickhouse-server
ln -s clickhouse local/usr/bin/clickhouse-server
```

Start again:
```
./clickhouse start --prefix local --user loyd
 chown -R loyd: 'local/var/run/clickhouse-server/'
Will run local/usr/bin/clickhouse-server --config-file local/etc/clickhouse-server/config.xml --pid-file local/var/run/clickhouse-server/clickhouse-server.pid --daemon
Waiting for server to start
Waiting for server to start
Waiting for server to start
Waiting for server to start
...
```

Some problems again...

I believe the process should be simpler.

**Comment by traceon** [comment]
> It's (5) problem, ok, fix

So what was exactly in `local/usr/bin/`?

> Some problems again...

What's in the logs?

**Comment by loyd** [comment]
> So what was exactly in `local/usr/bin/`?

As you've mentioned in (5), symlinks with prefix instead of just `clickhouse`.

```
ls -l local/usr/bin
total 1926272
-r-xr-xr-x 1 loyd loyd 1972495320 Jan 14 17:43 clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-benchmark -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-client -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-compressor -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-copier -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-extract-from-config -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-format -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-git-import -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-local -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-obfuscator -> local/usr/bin/clickhouse
lrwxrwxrwx 1 loyd loyd         24 Jan 14 17:43 clickhouse-server -> local/usr/bin/clickhouse
```

> What's in the logs?

Inside `local/var/log/clickhouse-server/clickhouse-server(.err).log` nothing.

Then, if I try to run `local/usr/bin/clickhouse-server --config-file local/etc/clickhouse-server/config.xml --pid-file local/var/run/clickhouse-server/clickhouse-server.pid --daemon`, I get empty  output and `0` exit code.

However, the same command without `--daemon` starts the server without visible errors/warnings in the output.

Do developers install clickhouse-server globally instead of using `--prefix`?

**Comment by traceon** [comment]
> However, the same command without --daemon starts the server without visible errors/warnings in the output.

That's interesting. Could be some new defect.

> Do developers install clickhouse-server globally instead of using --prefix?

Whatever combination of flags and values (or absence thereof) they use, apparently, they work for the corresponding use cases and environments. However, in general, the problems mentioned above exist. Feel free to open a PR that fixes #5. It should be pretty straightforward to implement.

**Comment by alexey-milovidov** [comment]
@loyd 

I don't install ClickHouse on my development machine.
I just created symlinks directly to my build directory:

```
$ ls -l /usr/bin/clickhouse*
lrwxrwxrwx 1 root root 57 ноя 26  2020 /usr/bin/clickhouse -> /home/milovidov/work/ClickHouse/build/programs/clickhouse
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-benchmark -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-client -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-compressor -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 ноя 26  2020 /usr/bin/clickhouse-copier -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 ноя 26  2020 /usr/bin/clickhouse-extract-from-config -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 июн  2  2020 /usr/bin/clickhouse-format -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 сен  7  2020 /usr/bin/clickhouse-git-import -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 72 мая  9  2021 /usr/bin/clickhouse-library-bridge -> /home/milovidov/work/ClickHouse/build/programs/clickhouse-library-bridge
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-local -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-obfuscator -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 69 июн 22  2020 /usr/bin/clickhouse-odbc-bridge -> /home/milovidov/work/ClickHouse/build/programs/clickhouse-odbc-bridge
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-performance-test -> /usr/bin/clickhouse
lrwxrwxrwx 1 root root 19 мар 15  2020 /usr/bin/clickhouse-server -> /usr/bin/clickhouse
```

So, I don't have to install ClickHouse after rebuild.

Also I created a symlink:
```
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ ls -l clickhouse-server
lrwxrwxrwx 1 milovidov milovidov 31 апр  8  2020 clickhouse-server -> ../../build/programs/clickhouse
```

And I run clickhouse-server simply by `./clickhouse-server` with no arguments.
Or even more simple, by pressing "Enter" in Midnight Commander.
