### ISSUE TITLE
remove experimental status of window functions

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#26396]
Blocking issues:

- [x] broken null handling, need to refactor to add deeper separation between window and aggregate functions https://github.com/ClickHouse/ClickHouse/issues/26115
- [ ] expression analyzer woes, not all expression dependencies are handled properly https://github.com/ClickHouse/ClickHouse/issues/24892
- [x] a mystery ubsan failure that doesn't reproduce https://github.com/ClickHouse/ClickHouse/issues/24184
- [x] a segfault found by fuzzer https://github.com/ClickHouse/ClickHouse/issues/25276
- [x] https://github.com/ClickHouse/ClickHouse/issues/26580

**Comment by macobo** [comment]
After this, will window functions also distribute across nodes?

**Comment by akuzm** [comment]
> After this, will window functions also distribute across nodes?

We don't have plans for this yet. I think one easy way to distribute would be to calculate window function on shards when the `PARTITION BY` of the window matches the sharding key.
