### ISSUE TITLE
TABLE OVERRIDE mechanism for Materialized databases

### ISSUE THREAD

**Issue by stigsb** [ClickHouse/ClickHouse#31480]
A general challenge with the Materialized* database engines is that DDL conversion sometimes result in very generic but very suboptimal schemas on the ClickHouse side. If users could supply a bit more direction based on knowing the application, the translated ClickHouse DDL could become more efficient.

To address this, I propose adding a mechanism to `CREATE DATABASE` for overlaying changes to columns (including indexes, constraints and projections) and storage (partition by, order by, sample by, etc.).  We have a working implementation of this in our internal fork, but I think it'd be good with an RFC before throwing in a pull request.

## Suggested Syntax

```
CREATE DATABASE test ENGINE=MaterializeMySQL('127.0.0.1:3306', 'test', 'root', 'clickhouse')
    TABLE OVERRIDE t1 (
        COLUMNS (
            -- sparse column list, replacing existing ones or adding new ones
            timestamp DateTime CODEC(DoubleDelta, Default)
            PROJECTION ...,
            CONSTRAINT ...,
            INDEX ...
        )
        -- storage parameters:
        ORDER BY expr
        PRIMARY KEY expr
        PARTITION BY expr
        SAMPLE BY expr
        TTL ...
    ),
    -- multiple tables can be overridden
    TABLE OVERRIDE t2 (
        PARTITION BY tuple(id % 10, toYYYY(created))
    )
```

## ALTERing overrides

Currently table overrides would have to be added before creating the database. To support schema evolution, it should be possible to add/modify/drop table overrides. For this, `ALTER DATABASE` queries are needed:

```
ALTER DATABASE test ADD TABLE OVERRIDE ..., DROP TABLE OVERRIDE ..., MODIFY TABLE OVERRIDE ...
```

Some of these changes are impossible (or impractical) to implement dynamically. It's fairly straightforward to handle ADD TABLE OVERRIDE for columns by running ALTER TABLE sub-queries. But for DROP/MODIFY TABLE OVERRIDE it's harder to construct such ALTER TABLE queries, because we no longer have the original schema. It could be possible to address this by storing the converted CREATE query (before applying overrides) in COMMENT or a new database property, but I'm not planning to address that in the coming PR.

ADD/DROP/MODIFY TABLE OVERRIDE queries that can not be applied dynamically can drop and re-create the database, if a new setting (for example `drop_and_recreate_database_if_needed`) is true. Otherwise, they will give an error:

```
ALTER DATABASE test DROP TABLE OVERRIDE t1 SETTINGS drop_and_recreate_database_if_needed=1
```

It should be possible to add a table override for a table that does not yet exist in the source database (MySQL)

## Task List

* [x] Implement CREATE TABLE TABLE OVERRIDE (apply to CREATE queries) - #32325
* [ ] Implement ALTER DATABASE {ADD | DROP | MODIFY} TABLE OVERRIDE
* [x] Implement EXPLAIN TABLE OVERRIDE for extra validation (to prevent overriding PARTITION BY with nullable columns etc.) - #32836
* [x] Add support for MaterializedPostgreSQL - #32749
* [ ] Apply overrides to ALTER queries
* [ ] Handle ALTER TABLE RENAME COLUMN
* [ ] Run validations provided by EXPLAIN TABLE OVERRIDE from CREATE interpreter
* [ ] Support EXPLAIN TABLE OVERRIDE for PostgreSQL

**Comment by stigsb** [comment]
Just changed the syntax by adding `COLUMNS` before the column overrides.
