### ISSUE TITLE
[Umbrella] Boosting the Projection feature

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#33678]
The Projection feature has been available for eight months now, and it's been used by several brave users under the experimental flag. I think it's time to make some dedicated effort to get it into a production-ready state.

The feature is tangled with many other core parts of ClickHouse, which results in several corner cases. The following list of tasks is ordered by priority:

## Make tests green (Required)

- [x] https://github.com/ClickHouse/ClickHouse/pull/30144 
- [x] https://github.com/ClickHouse/ClickHouse/issues/30146
- [x] https://github.com/ClickHouse/ClickHouse/issues/33010
- [x] https://github.com/ClickHouse/ClickHouse/issues/31401

## More features (Optional)

- [ ] Treat projection as real tables which can specify column codecs, indices, etc. Also allow to specify names of expressions to avoid too long file names. https://github.com/ClickHouse/ClickHouse/issues/28932, https://github.com/ClickHouse/ClickHouse/issues/34891.
- [ ] Allow to ALTER projection columns (add, drop). Only columns added by the ADD COLUMN command in the same ALTER query are allowed in newly added projection columns, without default column value. This is similar to ALTER ORDER BY.
- [ ] Make projection smarter. https://github.com/ClickHouse/ClickHouse/issues/24779, https://github.com/ClickHouse/ClickHouse/issues/24810, https://github.com/ClickHouse/ClickHouse/issues/26369, https://github.com/ClickHouse/ClickHouse/issues/32488, https://github.com/ClickHouse/ClickHouse/issues/32753, https://github.com/ClickHouse/ClickHouse/issues/35493
- [x] Support WHERE clause for projection. https://github.com/ClickHouse/ClickHouse/issues/33587
- [ ] TTL which leaves only projections or only the original data. https://github.com/ClickHouse/ClickHouse/issues/26578, https://github.com/ClickHouse/ClickHouse/issues/9436
- [ ] Indices via projection. https://github.com/ClickHouse/ClickHouse/issues/30530, https://github.com/ClickHouse/ClickHouse/issues/14694
- [ ] More use cases of projections for different types MergeTree engines https://github.com/ClickHouse/ClickHouse/issues/24778, https://github.com/ClickHouse/ClickHouse/issues/28311
- [ ] More types of projection engines https://github.com/ClickHouse/ClickHouse/issues/33615
- [ ] Allow putting projection parts into different storage media. This can be achieved after our cache mechanism. https://github.com/ClickHouse/ClickHouse/issues/28961
- [ ] ProjectionMergeTree https://github.com/ClickHouse/ClickHouse/issues/4419

The task list is not meant to be complete. Please feel free to add anything useful.

**Comment by inkrement** [comment]
Would it be possible to support LIMIT BY? A combination of ORDER BY/LIMIT BY would allow similar functionality as Replacing-MergeTree engine:

```sql
ALTER TABLE some.table ADD PROJECTION p_latest_version (
  SELECT
      *
  ORDER BY observed_at DESC
  LIMIT 1 BY id 
);
```

**Comment by amosbird** [comment]
@inkrement Is it the same to use the following aggregate projection?

```sql
ALTER TABLE some.table ADD PROJECTION p_latest_version (
  SELECT
      argMax((*), observed_at)
  GROUP BY id 
);
```

**Comment by inkrement** [comment]
It is! Thanks for this amazing solution; I was not aware of argMax, but seems super useful. Thanks for your great work!

**Comment by ywangtht** [comment]
Hi @amosbird ,
Seems like the aggregate-state function is not supported with projection.
e.g 
- Add an aggregate project with avg.
- This projection is not used when query with avgState.

Is this a known limitation?

**Comment by alexey-milovidov** [comment]
Duplicate of #58099.

**Comment by melvynator** [comment]
I'm reopening this issue, it's not really a duplicate. This GitHub issue tracks new features and feature enhancement; the other one, https://github.com/ClickHouse/ClickHouse/issues/58099 tracks the reliability issues of projections that need to be addressed in the next coming few months.

**Comment by alexey-milovidov** [comment]
@melvynator, there are only optional features remaining, and many of them are far-fetched (have zero chances of being implemented). Why don't just close to write it off?

**Comment by melvynator** [comment]
There are a few that could be useful to implement in the subsequent phases of our work on projections, but I agree that it is not a low-hanging fruit. We can return to them once we have improved the reliability of the feature. 

@amosbird Are you okay if we close this umbrella? We will work on extending projections features once we improve the reliability of it first.

**Comment by amosbird** [comment]
Yes, it is perfectly fine to close this umbrella.

**Comment by rfraposa** [comment]
@melvynator (or whomever) - the box next to "Support WHERE clause for projection" is marked as completed. Does that mean we can now add a `WHERE` clause to a projection?

**Comment by rubemz** [comment]
@melvynator do you know which version or how could I see which Clickhouse version started support a `WHERE` clause to a projection?
The version we are using (24.2.2.16288) doesn't look like support it

**Comment by rpstw** [comment]
There's no relative major code change for parsing a `WHERE` clause since Feb 2022, see https://github.com/ClickHouse/ClickHouse/commits/master/src/Parsers/ParserProjectionSelectQuery.cpp. For people seeking for `ADD PROJECTION SELECT WHERE`, I'm afraid it's unsupported as of now (Sep 2024)

**Comment by alexey-milovidov** [comment]
@amosbird, Yes, I expected that projections with WHERE work, but apparently they don't.
