### ISSUE TITLE
Features lost with moving to github actions

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#34694]
- [ ] ~Restore `clickhouse/clickhouse-client` docker image~ #37410 looks unnecessary unless the lightweight client is implemented
- [ ] ~Tagging testing on a green master once / X (1-5?)  days + lambda for packages repository cleanup~
- [ ] ~Make separate package for alpine with system dependencies from https://github.com/ClickHouse/sysroot/tree/bbcac834526d90d1e764164b861be426891d1743, something like `clickhouse-tiny-sysroot.apk`.~ I don't think we need it
- [ ] ~Move from DockerHub to GitHub docker repo for CI images.~ didn't need it for long
- [ ] ~Autoclean for testing deb/rpm/tgz repo~ testing is gone for good
- [x] update versions.tsv https://github.com/ClickHouse/ClickHouse/pull/34283
- [x] #35185
- [x] Redo alpine image building
- [x] #34742
- [x] #34741
- [x] Make `performance`, `release binary` and `release package` build artifacts from a single release build with `thinlto`. Now we do it three times... https://github.com/ClickHouse/ClickHouse/pull/36538
- [x] Restore coverage check https://github.com/ClickHouse/ClickHouse/pull/32854 https://github.com/ClickHouse/ClickHouse/pull/34895
- [x] Consider developing dashboard, see https://github.com/ClickHouse/ClickHouse/issues/34694#issuecomment-1046745018 - done in https://github.com/ClickHouse/ClickHouse/pull/48468
- [x] Update documentation how to build packages instead of `release` script, #36330 ([comment](https://github.com/ClickHouse/ClickHouse/pull/36330#issuecomment-1100661382)) https://github.com/ClickHouse/ClickHouse/pull/51679
- [x] Provide a source archive with submodules, like in https://github.com/ClickHouse/ClickHouse/releases/v21.7.3.14-stable/ https://github.com/ClickHouse/ClickHouse/pull/51435
- [ ] Add autorelease script with a schedule at most once / X (2? 3?) days to trigger testing/stable builds
- [ ] Add label `watch inactive` and close issues with it after 1 month inactivity

**Comment by qoega** [comment]
I really miss single page view of all check statuses. After GH Actions started posting their statuses to the list it became almost impossible to read. We never had one, but I guess it is usability degradation for now

**Comment by Felixoid** [comment]
It looks like we can use API handlers https://api.github.com/repos/ClickHouse/ClickHouse/statuses/6280efc0eb73fe4412241b7c4207af68f21c54a1?per_page=100 or https://api.github.com/repos/ClickHouse/ClickHouse/commits/d2cbc5af4026d1e18cca8ee77ca181d9a30c50d4/status?per_page=100

It displays only real statuses and not action runs.

**Comment by novikd** [comment]
Maybe instead of generating several task reports links for the GitHub list of run tests, we should generate just one page (again stored on S3) containing info about all run tests and links to the reports for each of them? I guess it'll make it easier to read test run results.

**Comment by Felixoid** [comment]
> Maybe instead of generating several task reports links for the GitHub list of run tests, we should generate just one page (again stored on S3) containing info about all run tests and links to the reports for each of them? I guess it'll make it easier to read test run results.

I am very much into it, there may be a small js script maybe, that would collect reports automatically. But, I am afraid, my frontend skills are close to null

**Comment by nickitat** [comment]
display actual test status. e.g. flaky displayed as failed not flaky.

**Comment by Felixoid** [comment]
Closing it in favor of the new ticket
