### ISSUE TITLE
Release script impovements

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#34900]
https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/release.py

TODO:

- [x] fetch branches automatically
- [x] (AS A TEMPORARY PROTECTION) remove the script from release branch to prevent it accidentally launched https://github.com/ClickHouse/ClickHouse/pull/35373/commits/602136c8d34aea9a0f16d04c13927fc0a58abd81 https://github.com/ClickHouse/ClickHouse/pull/40356/commits/8349b14d9dca886427badd7ef7b7d5f007ade81b https://github.com/ClickHouse/ClickHouse/pull/41669/commits/dde13a99cc550fa7bcca1501d6719cbbd4e159f7 and https://github.com/ClickHouse/ClickHouse/pull/42698/commits/9c2863b3a87d39822027c709ae76794aeb8cf86b
- [x] Add a check that the script is launched only from master #43017
- [x] Add a commit status to master and release branches `Release ready` that will depend on all necessary jobs. Do not create a release unless it exists and `success` #43017 and #43019
- [x] Add `sleep on second timeout reached` and/or `fetching tokens from smm` for `utils/changelog` script in new tag workflow #38238
- [x] add instruction
- [x] #45572
- [x] update `ARG VERSION=` arguments in `docker/server/Dockerfile.*` for the release.
- [x] add `utils/security-generator` to new tag (?) workflow #43365

Instruction draft for patch release:
* `git` and `gh` (https://github.com/cli/cli) should be installed
* fetch branch you want to release
* run `./release.py --type patch --commit 165eeeb50d477fc2621775da320c98c87998be15` (https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/release.py) master should be checked out
* when draft release appeared at [Releases](https://github.com/ClickHouse/ClickHouse/releases) page edit at and publish release
* PR _"Update version_date.tsv after ..."_ from [github-actions](https://github.com/apps/github-actions) bot should be merged into master

**Comment by Felixoid** [comment]
Add a post-actions:

- [ ] Publish a pre-created release
- [ ] Merge a pull-request for minor of major version updates

**Comment by Felixoid** [comment]
I close it in favor of the tiny latest issue, everything else is done here
