### ISSUE TITLE
Poco move to base/ + cleanup

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#46076]
Move the poco libraries from "contrib/" (+ a submodule of https://github.com/ClickHouse/poco) to "base/poco/" + clean up:

- [x] move libraries: #46075
- [x] remove unused or unwanted stuff from poco, right now it sits at ridiculous 1.8 mil. LOC
- [x] apply stricter compiler warnings (see `-w` in base/poco/CMakeLists.txt + further warning demotions in CMake files called from the top-level CMakeFile): #46133
- [x] cleanup poco CMake build description (e.g. remove variable LIBRARY_DIR from base/poco/CMakeLists.txt, use globbing where possible)
- [x] remove unused translation units and header files (First tried to remove some header/source files manually but poco is one big ball of mud ... even if a file is not used by ClickHouse, it is often used internally within poco. Then tried [`--print-gc-sections`](https://stackoverflow.com/a/9092009) but that showed that only negligible parts of Poco can be removed ... 😢 )
- [x] in #46075, some exclusions in checkers were expanded to explicit sub-paths, we should rather fix the found issues in poco and revert to the previous path spec (just "base/" instead of "base/glibc-compatibility,base/..."). Same for clang-tidy. #46133 #46155
- [x] apply ClickHouse code formatting to poco sources #46259
- [x] Archive https://github.com/ClickHouse/poco  (security team)
