### ISSUE TITLE
Mark MaterializedPostgreSQL as not experimental

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#49045]
to do that, close these issues:
- [x] https://github.com/ClickHouse/ClickHouse/issues/49586
- [x] https://github.com/ClickHouse/ClickHouse/issues/45891
- [x] https://github.com/ClickHouse/ClickHouse/issues/44453
- [x] https://github.com/ClickHouse/ClickHouse/issues/44250
- [x] https://github.com/ClickHouse/ClickHouse/issues/41923
- [x] https://github.com/ClickHouse/ClickHouse/issues/40556
- [x] https://github.com/ClickHouse/ClickHouse/issues/40262
- [x] https://github.com/ClickHouse/ClickHouse/issues/54918
- [x] https://github.com/ClickHouse/ClickHouse/issues/55251
- [x] https://github.com/ClickHouse/ClickHouse/issues/41922
- [x] https://github.com/ClickHouse/ClickHouse/issues/48039
- [x] https://github.com/ClickHouse/ClickHouse/issues/54297
- [x] https://github.com/ClickHouse/ClickHouse/issues/55421
- [x] https://github.com/ClickHouse/ClickHouse/issues/40449
- [x] https://github.com/ClickHouse/ClickHouse/issues/55098
- [x] https://github.com/ClickHouse/ClickHouse/issues/32902 (will not be implemented because can be substituted by https://github.com/ClickHouse/ClickHouse/issues/44252)
- [x] https://github.com/ClickHouse/ClickHouse/issues/47979
- [x] https://github.com/ClickHouse/ClickHouse/issues/52078
- [x] https://github.com/ClickHouse/ClickHouse/issues/59224
- [x] https://github.com/ClickHouse/ClickHouse/issues/39805
- [x] https://github.com/ClickHouse/ClickHouse/issues/45866
- [ ] https://github.com/ClickHouse/ClickHouse/issues/42149
- [x] https://github.com/ClickHouse/ClickHouse/issues/43153 (instead - add a setting to control this behaviour)
- [ ] https://github.com/ClickHouse/ClickHouse/issues/45507 (implement system.materialized_postgresql for errors and progress tracking)
- [ ] https://github.com/ClickHouse/ClickHouse/issues/58726
- [x] https://github.com/ClickHouse/ClickHouse/issues/59950
- [x] https://github.com/ClickHouse/ClickHouse/issues/62711
- [x] https://github.com/ClickHouse/ClickHouse/issues/64615
- [x] https://github.com/ClickHouse/ClickHouse/issues/59224
- [x] https://github.com/ClickHouse/ClickHouse/issues/64891
- [x] https://github.com/ClickHouse/ClickHouse/issues/66085
- [x] https://github.com/ClickHouse/ClickHouse/issues/66273

Issues with a opened PR, fixing the issue, but not yet merged:
- [x] https://github.com/ClickHouse/ClickHouse/issues/44252
- [x] https://github.com/ClickHouse/ClickHouse/issues/62691

**Comment by UnamedRus** [comment]
Fix backups for MaterializedPostgreSQL (https://github.com/ClickHouse/ClickHouse/issues/44252) ?

**Comment by alexey-milovidov** [comment]
MaterializedPostgreSQL cannot be production ready if #37924 is not reverted.

**Comment by kssenii** [comment]
> MaterializedPostgreSQL cannot be production ready if https://github.com/ClickHouse/ClickHouse/pull/37924 is not reverted.

https://github.com/ClickHouse/ClickHouse/pull/46106

**Comment by ToGoBananas** [comment]
https://github.com/ClickHouse/ClickHouse/issues/43186

I am unable to use MaterializedPostgreSQL integration because of the issue above

**Comment by CarlosLopezRoa** [comment]
@ToGoBananas 
https://knowyourmeme.com/photos/107227-i-know-that-feel-bro

**Comment by emmanuelm41** [comment]
Maybe add this issue too? 
https://github.com/ClickHouse/ClickHouse/issues/59224

**Comment by jpchev** [comment]
@kssenii: I see that Clickhouse bought PeerDB, which seems to have a good solution to push data from PostgreSQL to Clickhouse. Does this mean that Clickhouse team is planning to abandon the integrated MaterializedPostgreSQL engine? I hope this feature is still planned to be marked as production ready in the near future

**Comment by kssenii** [comment]
@jpchev, currently, making this feature non-experimental has been deprioritized in favor of other tasks. We don’t have immediate plan to work on this feature. But, for sure, not planning to abandon this feature. Will continue doing bug-fixes, though improvement-issues might have to wait for a while. Also there are still coming PRs with improvements for this engine from external contributors.
