### ISSUE TITLE
A list of proposed enhancements for Backup & Restore

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#49306]
These features will make the BACKUP and RESTORE queries even nicer:

- [x]  S3 Storage Class for backups (https://github.com/ClickHouse/ClickHouse/issues/48513)
- [ ]  DELETE BACKUP (https://github.com/ClickHouse/ClickHouse/issues/44199)
- [x]  MODIFY SETTINGS for table during RESTORE (https://github.com/ClickHouse/ClickHouse/issues/49304)
- [ ]  Server side copy for GCS (https://github.com/ClickHouse/ClickHouse/pull/49194)
- [ ]  Fix backups for MaterializePostgreSQL (https://github.com/ClickHouse/ClickHouse/issues/44252)
- [x] BACKUP TO AzureBlobStorage (https://github.com/ClickHouse/ClickHouse/issues/50747)
- [x] Persistent system backup table (https://github.com/ClickHouse/ClickHouse/issues/43995)
- [x] KILL BACKUP https://github.com/ClickHouse/ClickHouse/issues/52092

**Comment by Jin-H** [comment]
I think this can be add to feature

https://github.com/ClickHouse/ClickHouse/issues/43995

**Comment by goelrajat** [comment]
Currently, when I take backup on s3 using BACKUP command, the meta files are saved in local disk eg. /var/lib/clickhouse/disks/<s3_disk/
folder and the actual data is stored on s3. What is the recommended process of managing this meta zip or folder on local disk. IIMO, clickhouse should backup the meta folder as well on s3.

**Comment by UnamedRus** [comment]
> Currently, when I take backup on s3 using BACKUP command, the meta files are saved in local disk eg. /var/lib/clickhouse/disks/<s3_disk>/

You need to use https://clickhouse.com/docs/en/operations/backup#configuring-backuprestore-to-use-an-s3-endpoint
