### ISSUE TITLE
Correctess check for Math (Statistics) functions against state of art implementation (scipy)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#51275]
**Use case**

Something like https://github.com/ClickHouse/ClickHouse/issues/20481, but for mathematics. 

**Describe the solution you'd like**

Populate with (semi?)random data
Compare the results of ClickHouse with Python scipy (or something similar).
```[tasklist]
### Tasks
- [x] Mann-Whitney U test, studentTTest, welchTTest   https://github.com/ClickHouse/ClickHouse/pull/16883
- [x] kolmogorovSmirnovTest  https://github.com/ClickHouse/ClickHouse/pull/48325
- [ ] skew, kurtosis
- [ ] theilsU, cramersV, contingency
- [ ] meanZTest
- [ ] quantileTDigest
- [ ] quantileGK
```

**Comment by UnamedRus** [comment]
Whole test suite for skewPop/skewSamp is only one query against one dataset, which is matching ClickHouse implementation of that math function via common operators like +/*- 
And return result of 0, (ie symmetric)

https://github.com/ClickHouse/ClickHouse/blob/1cf3d3837324c64279770443a316f199ff299c00/tests/queries/0_stateless/00181_aggregate_functions_statistics.sql#L36-L69


https://github.com/ClickHouse/ClickHouse/blob/1cf3d3837324c64279770443a316f199ff299c00/tests/queries/0_stateless/00181_aggregate_functions_statistics.sql#L97-L112

**Comment by tavplubix** [comment]
We already do this See, for example, https://github.com/ClickHouse/ClickHouse/blob/df97f5890a115b8a4ee495f677c58c2818ad0c1e/tests/queries/0_stateless/02706_kolmogorov_smirnov_test_scipy.python

Feel free to open a PR that adds similar tests for other functions

**Comment by tavplubix** [comment]
Seems like it was closed by mistake. It makes sense to add such tests for the remaining functions

**Comment by alexey-milovidov** [comment]
We don't have such plans. If @UnamedRus wants, he can add it.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/87831
