### ISSUE TITLE
[Umbrella] Parallel replicas

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#54324]
- [x] https://github.com/ClickHouse/ClickHouse/issues/54276
- [ ] https://github.com/ClickHouse/ClickHouse/issues/54304
- [x] https://github.com/ClickHouse/ClickHouse/issues/53595 https://github.com/ClickHouse/ClickHouse/issues/54300

Parallel replicas over distributed:
- [x] doesn't work correctly with `prefer_localhost_replica=1` https://github.com/ClickHouse/ClickHouse/pull/54334

Fuzzing:
- [x] https://github.com/ClickHouse/ClickHouse/issues/54314
- [x] https://github.com/ClickHouse/ClickHouse/issues/54325 

Performance:
- [ ] Parallel replicas should improve ClickBench
- [ ] Distributed INSERT SELECT for parallel replicas

**Comment by devcrafter** [comment]
The parallel replicas issues are tracked via project now
