### ISSUE TITLE
[Umbrella] Projections Reliability Improvements

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#58099]
Projections are widely adopted by the community, but one of the main drawbacks of this feature is the reliability aspect of it. The lack of support and guardrails around some features make it easy for a user to be negatively impacted by the projections. In order to make the feature more safe and reliable we need to prioritize the implementation of fixes and addition of guardrails around features that are not supported by projections:

## P1:
- [ ] https://github.com/ClickHouse/ClickHouse/issues/50991

## P2:
- [ ] https://github.com/ClickHouse/ClickHouse/issues/24778
- [ ] https://github.com/ClickHouse/ClickHouse/issues/56593
- [ ] https://github.com/ClickHouse/ClickHouse/issues/46968

## Low priority (moved to phase 2 if cannot be done in phase 1):
- [ ] https://github.com/ClickHouse/ClickHouse/issues/49790
- [ ] https://github.com/ClickHouse/clickhouse-private/issues/4021
- [ ] https://github.com/ClickHouse/clickhouse-private/issues/3765
- [ ] https://github.com/ClickHouse/ClickHouse/issues/33684
- [ ] https://github.com/ClickHouse/ClickHouse/issues/32753

cc: @amosbird

**Comment by nikitamikhaylov** [comment]
Another umbrella ☂️: https://github.com/ClickHouse/ClickHouse/issues/33678

**Comment by melvynator** [comment]
It's raining in the projections world. 

This one has a focus on making it more reliable rather than extending the features.

**Comment by UnamedRus** [comment]
It would be also nice to decouple projection folder name from it's name if it's too long https://github.com/ClickHouse/ClickHouse/issues/47320#issuecomment-1865017304

**Comment by beda42** [comment]
I would suggest that the simplest way to add guardrails around projections would be to mention the limitations in the official projections documentation.

**Comment by alexey-milovidov** [comment]
Closing as all high-priority tasks are done.
