### ISSUE TITLE
[Umbrella] Refreshable Materialized View

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#59095]
```[tasklist]
### Tasks
- [x] Remove the usage of `std::weak_ptr` for IStorage: https://github.com/ClickHouse/ClickHouse/pull/58934
- [x] `Replicated` databases are not supported, but for some reason it's possible to create a Refreshable MV it there: https://github.com/ClickHouse/ClickHouse/pull/60669
- [x] Refreshable MV does EXCHANGE all the time, but ReplicatedMergeTree can have some leftovers in [Zoo]Keeper: https://github.com/ClickHouse/ClickHouse/issues/61065
- [x] RENAME EXCHANGE support: https://github.com/ClickHouse/ClickHouse/issues/61826
```
