### ISSUE TITLE
Analyzer: Broken performance tests

### ISSUE THREAD

**Issue by novikd** [ClickHouse/ClickHouse#62245]
# Changes in performance

- [ ] direct_dictionary
- [ ] materialized_view_parallelize_output_from_storages
- [ ] agg_functions_argmin_argmax
- [ ] materialized_view_parallelize_output_from_storages
- [ ] order_by_read_in_order
- [ ] agg_functions_argmin_argmax
- [ ] distinct_combinator
- [ ] low_cardinality_query
- [ ] agg_functions_min_max_any
- [ ] website
- [ ] count
- [ ] merge_tree_simple_select
- [ ] injective_functions_inside_uniq
- [ ] if_transform_strings_to_enum
- [ ] arithmetic_operations_in_aggr_func
- [ ] push_down_limit
- [ ] set_index
- [ ] uniqExactIf

# Backward incompatible queries

- [ ] array_reduce
- [ ] quantile_merge
- [ ] scalar2
- [ ] dotProduct
- [ ] array_fill
- [ ] norm_distance

# References to reports

1. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[1_4]/report.html
2. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[2_4]/report.html
3. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[3_4]/report.html
4. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[4_4]/report.html

**Comment by vdimir** [comment]
Tests `array_reduce`, `quantile_merge` and `array_fill` are not incompatible, it just generate big constant arrays with `range` function.

We can make a hotfix, until proper fix for constants in analyzer is ready, https://github.com/ClickHouse/ClickHouse/pull/62273

**Comment by novikd** [comment]
@vdimir I took the description from the performance test reports. Probably it's a good idea to make those queries _"runable"_ with a hot fix and continue the work on the constants refactoring.

**Comment by antaljanosbenjamin** [comment]
`agg_functions_argmin_argmax` is fixed by https://github.com/ClickHouse/ClickHouse/pull/64793. In cloud I couldn't measure the difference, but in locally I was able to measure the difference.

Basically `agg_functions_argmin_argmax #0` speed up by ~21%, `agg_functions_argmin_argmax #4` speed up by ~10%. In the linked performance comparison report the respective slow down was ~28% and ~13%. They are a bit bigger numbers then my measurements show, but most importantly the queries run the same with and without the analyzer.

![image](https://github.com/user-attachments/assets/8fcb60ae-b28e-4ab0-8676-62d5b2bdde93)


# `agg_functions_argmin_argmax #0`

<details>

Before the PR with analyzer:
```
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.480
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.435
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.442
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.480
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.462
```
Before the PR without analyzer:
```
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.229
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.195
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.218
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.196
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.189
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.207
```
After the PR with analyzer:
```
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.220
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.206
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.194
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.234
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.205
```

After the PR without analyzer:
```
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.212
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.216
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.222
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.243
$ ./clickhouse client --query "select argMin(Title, EventTime) from hits_100m_obfuscated  where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.241
```
</details>

# `agg_functions_argmin_argmax #4`

<details>

Before the PR with analyzer:
```
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
2.036
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.992
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
2.021
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
2.047
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
2.023
```

Before the PR without analyzer:
```
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.850
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.835
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.830
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.832
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.856
```

After the PR with analyzer:
```
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.812
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.802
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.796
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.828
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=1 FORMAT Null" --time
1.828
```

After the PR without analyzer:
```
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.898
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.778
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.840
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.798
$ ./clickhouse client --query "select argMin((Title, RegionID), EventTime) from hits_100m_obfuscated where Title != '' group by intHash32(UserID) % 1000000 SETTINGS allow_experimental_analyzer=0 FORMAT Null" --time
1.856
```
</details>

I will check more tests too.

**Comment by antaljanosbenjamin** [comment]
BTW, I used [this query](https://play.clickhouse.com/play?user=play#U0VMRUNUICdodHRwczovL3MzLmFtYXpvbmF3cy5jb20vY2xpY2tob3VzZS10ZXN0LXJlcG9ydHMvJyB8fCBwdWxsX3JlcXVlc3RfbnVtYmVyIHx8ICcvJyB8fCBjb21taXRfc2hhIHx8ICcvcGVyZm9ybWFuY2VfY29tcGFyaXNvbl9bMl80XS9hbGwtcXVlcmllcy5odG1sJyBBUyB1cmwsIGNoZWNrX3N0YXJ0X3RpbWUgRlJPTSBjaGVja3MgV0hFUkUgMQogICAgLS0gQU5EIGNvbW1pdF9zaGEgPSAnNzk1MWE3MmU0NTQ4NjExNWU2MmM5YzlhZDhjYWY2MjZkMDE2YjE1YScKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIGNoZWNrX25hbWUgPSAnUGVyZm9ybWFuY2UgQ29tcGFyaXNvbiBbMi80XScKICAgIEFORCB0ZXN0X25hbWUgTElLRSAnJwogICAgQU5EIGluc3RhbmNlX3R5cGUgPSAncjZhLjR4bGFyZ2UnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQwpMSU1JVCAxMjAK) in our CI DB to find the performance reports that are run on the same instance type as the linked performance reports and it made easy to narrow the range of PR I had to look through. It might be useful for somebody for this task or maybe for soemthing else.

**Comment by novikd** [comment]
@yakov-olkhovskiy finished #63198, so it is now worth rerunning performance tests against the old analyzer. Also, all report links don't work anymore.
I created #74127 to check it.

**Comment by novikd** [comment]
I'm moving the previous report to a separate comment for historical reasons.

# Changes in performance (as of release 24.3)

- [ ] direct_dictionary
- [ ] materialized_view_parallelize_output_from_storages
- [ ] materialized_view_parallelize_output_from_storages
- [ ] order_by_read_in_order
- [x] agg_functions_argmin_argmax - Both queries fixed by https://github.com/ClickHouse/ClickHouse/pull/64793.
- [x] distinct_combinator #65110
- [ ] low_cardinality_query
- [x] agg_functions_min_max_any - Both queries fixed by https://github.com/ClickHouse/ClickHouse/pull/64793.
- [ ] website
- [ ] count
- [ ] merge_tree_simple_select
- [x] `injective_functions_inside_uniq` #65140
- [x] if_transform_strings_to_enum #62558
- [x] `arithmetic_operations_in_aggr_func` #65104
- [x] `push_down_limit` #68410

## May be fixed by constant refactoring
- [ ] `uniqExactIf` -- Big constant after scalar subquery execution
- [ ] `set_index` -- Big constant sets

# Backward incompatible queries

- [ ] `array_reduce` requires constants refactoring
- [ ] `quantile_merge` requires constants refactoring
- [ ] `array_fill` requires constants refactoring
- [x] `scalar2` #62281
- [x] `dotProduct` #62281
- [x] `norm_distance` #62281

# References to reports

1. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[1_4]/report.html
2. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[2_4]/report.html
3. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[3_4]/report.html
4. https://s3.amazonaws.com/clickhouse-test-reports/61652/7951a72e45486115e62c9c9ad8caf626d016b15a/performance_comparison_[4_4]/report.html

**Comment by antaljanosbenjamin** [comment]
I spent some time on the first group. My observations:

1. The difference in the plan is an extra `SquashingTransform` in case we are using the new analyzer.
2. Locally it is kind of hard to reproduce it with clang-19 (RelWithDebInfo build), but I managed to reproduce a 7% difference in the query of `join_append_block` by increasing the right table size from 100mil to 400mil. See the attached picture.
3. For the rest of the queries I couldn't reproduce any significant different locally.
4. I tried to get rid of the squashing transform, but the performance got even worse.
5. I tried to use XRay as profiler, but it messed up the execution time so much that I don't think the output is usable.
6. I [tried](https://pastila.nl/?000b91c9/59e2770d1d42e34ef4452a0b94eaec17#pQYLljAFXR6KUqRhXp76ug==) our built in query profiler with trace log, but I couldn't spot any obvious issues. 

![Image](https://github.com/user-attachments/assets/a38440cb-6fbe-4825-954e-74ed50cf54d6)

**Comment by novikd** [comment]
I checked the output of the Perf test for `direct_dictionary` query 0, and it contains flamegraphs. From there, I could see that we spend quite a lot of time (41%) inside of `QueryTreeBuilder::buildExpression` building a column for the tuple.

![Image](https://github.com/user-attachments/assets/ca16f8a4-48b7-48c0-8035-5e89e0ab153a)

**Comment by alexey-milovidov** [comment]
Optimization for constants has been merged. Please update the list of tests that are still pending.
