### ISSUE TITLE
Roadmap 2025

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#74046]
This is ClickHouse roadmap 2025.

This roadmap does not cover the tasks related to infrastructure, orchestration, documentation, marketing, external integrations, drivers, etc.

See also:

Roadmap 2024: https://github.com/ClickHouse/ClickHouse/issues/58392
Roadmap 2023: https://github.com/ClickHouse/ClickHouse/issues/44767
Roadmap 2022: https://github.com/ClickHouse/ClickHouse/issues/32513
Roadmap 2021: https://github.com/ClickHouse/ClickHouse/issues/17623
Roadmap 2020: [link](https://github.com/ClickHouse/ClickHouse/blob/be29057de1835f6f4a17e03a422b45b81efe6833/docs/ru/whats-new/extended-roadmap.md)

## Data Lakes

- [x] Automatic use of cluster functions #70659
- [x] Parallel distributed INSERT SELECT by default #80425
- [x] Enable Hive-style partitioning by default #71636
- [x] Uniform distribution of load across cluster #70190
- [x] Partition pruning for Iceberg #72044
- [x] Prewhere support for Parquet #65527
- [x] Unify different Parquet readers into one #70611
- [x] Writing bloom filters for Parquet #71681
- [x] Time travel for Iceberg #71072
- [x] Support for deletions in Iceberg #66588 #83627
- [x] In-memory metadata cache #71579
- [x] Integration with Delta kernel #75255
- [x] Glue catalog support #76988
- [x] Unity catalog support #77257
- [x] Support for Delta Lake on Azure #74541
- [ ] Materialized views on top of data lakes
- [ ] Support arbitrary nesting in database and table names #71171
- [x] Writing into data lakes #49973
- [ ] Background merges for data lakes ☁ 
- [x] Subsets of a large file as a unit of work

## Query Engine

- [x] Non-constant CASE, non-constant IN #65398
- [ ] Using a partition key to optimize JOINs
- [ ] Optimization of anti-joins: LEFT JOIN ... WHERE ... IS NULL to NOT IN
- [ ] Deriving index condition from the right-hand side of INNER JOIN
- [ ] Automatic JOINs in external memory, if needed
- [ ] Optimization for certain cases of distributed JOINs
- [x] JOIN reordering based on finer-grained statistics
- [x] Correlated subqueries with decorrelation #66143 #76078
- [x] PREWHERE to work with the FINAL clause #70210
- [x] Secondary indices to work with the FINAL clause #70292
- [ ] Support for certain SQL functions without parentheses #52102
- [x] Unification of table structures in Merge tables #73956
- [ ] Optimizations for a single dictionary in LowCardinality #72717
- [ ] Materialized CTE #61086
- [x] Query conditions cache #69236
- [x] Userspace page cache #70509
- [x] Lazy columns #55518
- [ ] Block-level hints #48800
- [ ] Query cache for partial results #57490
- [ ] On-disk query cache #52141
- [ ] Streaming queries #63312

## Data Storage

- [x] JSON data type from beta to production #77785 See https://jsonbench.com/
- [ ] Unique key constraint #70589
- [x] Lightweight updates with patch parts #82004
- [ ] Automatic LowCardinality columns #69916
- [x] Secondary indices by default #72090
- [ ] ShardedMap data type #47045
- [x] Time data type #71943
- [ ] Unify statistics with secondary indices
- [x] Production-ready full-text index #86485
- [ ] Functions and codecs for quantization
- [x] Production-ready vector search
- [x] Allow to instantly attach backups #64222
- [ ] Transactions for Replicated tables

## Interfaces

- [x] Random early drop on overload #63206
- [x] Resource scheduler by CPU #77595
- [x] Support for PromQL #75036
- [ ] Configuration of query handlers with SQL
- [ ] Remote and Cloud database engines #59304
- [ ] Drivers for UDFs #71172
- [ ] API for query construction #64336
- [ ] Even simpler data upload #38775
- [ ] Passing input data to the url table function #45994
- [x] Support for TLS in the PostgreSQL wire protocol #73812
- [ ] Support for HTTP Event-Stream
- [x] Persistent databases in clickhouse-local #71722
- [x] Implicit tables in clickhouse-local #65023
- [x] SSH protocol for the server #48902
- [ ] Predictive autocomplete in the CLI #69641

## Cleanups

- [ ] Remove old analyzer
- [ ] Remove old predicate pushdown mechanics
- [x] Remove Object data type in favor of JSON
- [ ] Remove Window View in favor of streaming queries
- [x] Remove Live View in favor of streaming queries
- [x] Remove the old cache for Hive #77795
- [x] Remove the "send metadata" feature #82508

**Comment by JackyWoo** [comment]
> JOIN reordering based on finer-grained statistics
@alexey-milovidov do you plan to introduce CBO optimizer for the feature?

**Comment by JackyWoo** [comment]
@alexey-milovidov Thank you. @KochetovNicolai may I ask how can I reach you? PS: you can find my email in my github personal page.

**Comment by VincentS** [comment]
@alexey-milovidov  Do you have any update about `Support for PromQL` in Clickhouse or ETA ?

**Comment by alexey-milovidov** [comment]
@VincentS, PromQL is being actively implemented by @vitlibar. There is a large amount of work, and I expect it in the second half of the year.

**Comment by yahoNanJing** [comment]
Is there any plan to open source the light weight update?

**Comment by yahoNanJing** [comment]
Thanks @alexey-milovidov. Is there any existing work for this? And could you help list the related issues and PRs?

**Comment by chenbay** [comment]
@alexey-milovidov  hey guy，i want to see this Data Storage feat  ShardedMap data type https://github.com/ClickHouse/ClickHouse/pull/47045  in next month release.  :-)  can i ？

**Comment by mattxuer** [comment]
Is there any works on fixing clickpipes interface with a searchable grid and a disable and enable all button or maybe an api that we call to automate our requests?

**Comment by Ryado** [comment]
@mattxuer Yes! we have an API in the works that will come with a Terraform provider. If you are interested in early access you can drop me a note at ryadh [at] clickhouse.com

cc. @laeg

**Comment by mattxuer** [comment]
Yes please :)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kotik-adjust** [comment]
Can we expect any improvements to the Kafka Engine in 2025?

**Comment by alexey-milovidov** [comment]
@kotik-adjust, Improvements for the Kafka engine are not in the main roadmap but in the experimental tasks: https://github.com/ClickHouse/ClickHouse/issues/71175

**Comment by include** [comment]
From the docs [https://clickhouse.com/docs/en/engines/table-engines/integrations/s3] I read "(...) querying from S3 tables that are partitioned is not directly supported (...)" is this going to be addressed? Thanks

**Comment by AndrewRazumovskiy** [comment]
It would be nice to have feature like Postgres NOTIFY (pg_notify)

**Comment by AndrewRazumovskiy** [comment]
add column type like rawblob/binary to save raw data ,like pictures/pdf/xlsx etc, in binary formats, not as string

**Comment by alexey-milovidov** [comment]
@AndrewRazumovskiy, `String` in ClickHouse stores arbitrary binary data. I use it to backup my photos from travel: https://github.com/ClickHouse/ClickHouse/blob/master/utils/backup/backup

There is absolutely no need for a separate BLOB data type. Moreover, when you type BLOB in ClickHouse, it is automatically interpreted as `String`.

**Comment by ddulesov** [comment]
Query streaming feature that would greatly enhance ClickHouse capabilities , enabling real-time results for large datasets and interactive analytics. Could the team consider adding this to the roadmap for 2025?

**Comment by alexstanovoy** [comment]
I want to cast my vote for Query streaming.
https://github.com/ClickHouse/ClickHouse/pull/63312
It's becoming a must-have for us on our scale.

**Comment by hugocatlas** [comment]
+1
Something like Proton is doing.
It would be interesting to have their functionalities integrated into ClickHouse natively

**Comment by igkg** [comment]
Could you please add [MAC ](https://github.com/ClickHouse/ClickHouse/issues/76309) data type by UUID analogy?

**Comment by karthik-thiyagarajan** [comment]
@alexey-milovidov  One of the critical piece of work that we have been seeing quite often is that we are unable to create DDL atomically (add columns, drop columns and rename column )  across all replicas. This creates problems to have inconsistent ddls across multiple replicas.  Historically we have been seeing that the mutations are not getting created if ZK is busy or if CH is very busy and eventually getting timed out. Is it possible to add this if this is not too much to ask ?

**Comment by larry-cdn77** [comment]
Exciting road map 👍

A little bit on transactions will go a long way

My next vote after replicated engine transactions would be transactions across materialized views

**Comment by AndrewRazumovskiy** [comment]
Add possibility to specify asc/desc for ReplacingMergeTree(ver). Currently greatest 'ver' always wins, good to have if "first" wins

**Comment by tanner-bruce** [comment]
https://github.com/ClickHouse/ClickHouse/issues/8168 - would be very useful for querying observability data like `timestamp BETWEEN .. AND .. AND (x = 1 OR y = 2)`

**Comment by 29antonioac** [comment]
Hi, is there any plan to optimise timestamp range joins?  It would be great for time series data. Duckdb has an efficient implementation https://duckdb.org/2022/05/27/iejoin.html

**Comment by Neyzoter** [comment]
> Production-ready full-text index

Which month will the production-ready full-text index release?

**Comment by astronautas** [comment]
No SharedMergeTree for OSS :(?

**Comment by vanand-rcc** [comment]
Any possibility to skip loading/validating Views into memory at the time of server startup and simply refer the view from the .sql file every time the view is queried?   Our setup requires lot of views (few thousands) and each view is consuming few MB of RAM even at idle.

**Comment by AndrewRazumovskiy** [comment]
Add param to "start with" for generateSerialID:
`id UInt64 DEFAULT generateSerialID('MyCounter', 100)`
next value is 101

**Comment by alexey-milovidov** [comment]
Roadmap 2026: https://github.com/ClickHouse/ClickHouse/issues/93288
