### ISSUE TITLE
20.2 release checklist

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8989]
- [x] Check that curl library still works with remote S3 service, ask Alexander Burmak -- fix in #9039
- [x] Fix the issue with "cannot create ColumnFunction", ask @4ertus2 and Vitaly Orloff from Yandex Morda; #8689 -- fix in #9010
- [x] Ensure Vasily Nemkov has fixed trash unit tests or: hide DoubleDelta and Gorilla codecs under experimental flag -- fix in #9028
- [x] UBSan fuzz test report: https://clickhouse-test-reports.s3.yandex.net/0/3c1735d996594c222a03046eaa033d92f6e6bac1/functional_stateless_tests_(ubsan).html #9246
- [x] fix or revert JSON square brackets #8948 -- fix in #8958
- [x] fix SSL timeouts in Poco with query profiler -- fix in #9026
- [x] fix incorrect type serialized in T64 codec -- fix in #9033
- [x] mutation breaks index #8982 -- fix in #9048
- [x] FlatDictionary related segfault #9040
- [x] RangeReader wrong number of rows #8964 -- fix in #9050 
--- Fixed
- [x] Confirm that recent performance degradation on performance test is related to the internal issue of Sandbox CI (they have trouble after updating atop);
- [x] Fix segfault in RangeReader. #8997
- [ ] Segfault in stress test: https://clickhouse-test-reports.s3.yandex.net/9211/b2a52a2d6980e4ccf4cfd4f2d71b3da291616527/stress_test_(thread).html
- [x] key condition negated incorrectly for monotonic functions #9034 -- a 2-year old bug, can release without fix
- [x] Fix the issue about entropy in OpenSSL https://github.com/ClickHouse/ClickHouse/issues/8573 https://github.com/ClickHouse/ClickHouse/issues/8886;
- [x] ASan report: https://clickhouse-test-reports.s3.yandex.net/0/94b52c08582a1f8e91e8246714dd323f4bf8a17b/functional_stateless_tests_(address)/stderr.log

**Comment by alesapin** [comment]
`> Confirm that recent performance degradation on performance test is related to the internal issue of Sandbox CI (they have trouble after updating atop);`
https://clickhouse-test-reports.s3.yandex.net/8303/8129cd2445ceba0e879f6700b1d895d4ff6a38fa/performance_test.html

We have a lot of successful reports on master after they rolled back atop release.

**Comment by alesapin** [comment]
> key condition negated incorrectly for monotonic functions #9034 -- a 2-year old bug, can release without fix

This seems like a blocker for 20.2, but not for patch versions 20.1 and 19.17.

**Comment by akuzm** [comment]
UBSan fuzz test report: https://clickhouse-test-reports.s3.yandex.net/0/3c1735d996594c222a03046eaa033d92f6e6bac1/functional_stateless_tests_(ubsan).html

-- cannot reproduce.
Tried last two queries:
```
:) SELECT CAST(CAST(((SELECT dictGetDate('\0', NULL)), (SELECT log(-708, CAST(CAST(-2.597, 'String'), 'Date'))) AS dzj), 'Date'), 'String')
:)  SELECT * FROM merge('', 'F')
```
Both are ok. 

Server log is truncated, no mention of abort there, probably it just calls exit(). Will add `abort_on_error=1` to ubsan options, as we did with tsan.

**Comment by alexey-milovidov** [comment]
It's about dangling reference (use after free) of Context in StorageFile:

```
    #0 0x1e22a18e in DB::Context::getApplicationType() const /build/obj-x86_64-linux-gnu/../dbms/src/Interpreters/Context.cpp:1969:20
    #1 0x1f2a673d in DB::getInputFormatSetting(DB::Settings const&, DB::Context const&) /build/obj-x86_64-linux-gnu/../dbms/src/Formats/FormatFactory.cpp:63:98
    #2 0x1f2a5a79 in DB::FormatFactory::getInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadBuffer&, DB::Block const&, DB::Context const&, unsigned long, std::__1::function<void ()>) const /build/obj-x86_64-linux-gnu/../dbms/src/Formats/FormatFactory.cpp:156:42
    #3 0x1ed20949 in DB::StorageFileBlockInputStream::readImpl() /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageFile.cpp:257:48
```

**Comment by alexey-milovidov** [comment]
> probably it just calls exit()

Yes, all sanitizers print to stderr and exit.

**Comment by akuzm** [comment]
> It's about dangling reference (use after free) of Context in StorageFile:

The stack is similar to the thing that we've seen under msan recently: https://pastebin.com/raw/tTxCDFKp
@tavplubix knows the reason, but I think he haven't fixed it yet.

**Comment by ssserj** [comment]
@alexey-milovidov please, try to fix issue #8890 in 20.2 release. Can't work properly (expire policy doesn't work) with external dictionaries with `source_type` DBMS::MySQL at now.

**Comment by alexey-milovidov** [comment]
> FlatDictionary related segfault

It was induced bug, does not reproduce anymore.

**Comment by alexey-milovidov** [comment]
> @alexey-milovidov please, try to fix issue #8890 in 20.2 release. Can't work properly (expire policy doesn't work) with external dictionaries with source_type DBMS::MySQL at now.

We'll try.
