### ISSUE TITLE
20.4 release checklist

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#9843]
Known degradations in master:
- [x] #9914 HTTP GET is not readonly
- [x] #9839 JOIN ... GROUP BY ... WITH TOTALS throwing exception on join
- [x] #9826 Different results are returned at every execution by executing same query which contains several UNIONs and JOINs in version
- [x] #9699 mysql() table function + join = broken after update to 20.3.1.2564
- [x] #9714 #9672 Different results while aliasing expression to column name on distributed table engine.
- [x] #9810 Second argument to CAST must be a constant string describing type
- [x]  #9863 'COMMA to CROSS JOIN rewriter is not enabled or cannot rewrite query' 
- [x] #10092 PREWHERE cannot contain ARRAY JOIN or JOIN action
- [x] #10106 Alters are broken with compact parts (not strictly necessary)
- [x] #8109 ALTER UPDATE with lambda expressions doesn't work for replicated tables (not strictly necessary)
- [x] #10259 Logical error: 'Invalid number of columns in chunk pushed to OutputPort. Expected 3, found 4
- [x] #10302 regression in expression chain finalize logic
- [x] Fix segfault with distributed_group_by_no_merge #10399
- [x] Change max_server_memory_usage from user level to server level setting (for Metrica). #10421
...
- [x] #10583 Column with Array type is not represented by ColumnArray column (crash)
- [x] #10655 Consecutive execution of distributed queries

**Comment by AndLLA** [comment]
Please add the fix for memory consumption on delete mutations (#9860)

**Comment by qoega** [comment]
@AndLLA this problem is already fixed. And will be merged as bugfix to 20.1 and 20.3 afaik.

**Comment by alexey-milovidov** [comment]
All done (as of now).
More issues to be found.

**Comment by alexey-milovidov** [comment]
One critical performance issue has been found: https://github.com/ClickHouse/ClickHouse/issues/10655

**Comment by den-crane** [comment]
@alexey-milovidov what about https://github.com/ClickHouse/ClickHouse/issues/10566 ?

**Comment by alexey-milovidov** [comment]
It also looks like a critical issue. I see that a pull request with fix is already here.
A bug that was fixed quickly is not a bug at all.

**Comment by azat** [comment]
Consider looking into the following two (at least):
- #10486 
- #10516 
 
(Since the functionality had been added in 20.4, and those are fixes)
