### ISSUE TITLE
TPC-DS compatibility issues

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#9887]
TPC-DS check list in 20.3+.

Missing features:
- [x] INTERSECT / EXCEPT operators not implemented **fixed via #24757 in 21.9**
- [x] [NOT] EXISTS-operator not implemented #6852 **fixed via #29731 in 21.11**
- [x] Interval syntax like '+ 30 days' is not supported **fixed via #15978 in 20.11**
- [x] CTE syntax is different from ANSI SQL 99 **fixed via #14771 in 20.10?**
- [x] CTE returning multiple rows is not supported #2416 **partially fixed via #14771 in 20.10?**
- [x] Window  functions are not supported (OVER ... PARTITION BY ... ) #1469
- [ ] Missing analytical functions RANK, FIRST, LAST, LAG **the exact syntax is not supported but can be emulated using existing toolset**
- [x] [GROUPING SETS](https://docs.microsoft.com/en-us/sql/t-sql/functions/grouping-transact-sql?view=sql-server-ver15)  #33631 **22.5**
- [x] GROUPING specification for ROLLUP, CUBE and GROUPING SETS; #37163 **22.6**
- [x] Correlated subqueries are not supported (Missing columns: "x" while processing query) #6697 #9861

Bugs:
- [x] count(*) is not supported for multiple join queries #9853 **fixed via #10291 in 20.3.8**
- [x] COMMA to CROSS JOIN rewriter is not enabled or cannot rewrite query #9863 **fixed via #9830 in 20.3.5**
- [x] Mix of COMMA and other JOINS is not supported #9864 **fixed via #9830 in 20.3.5**
- [x] illegal type FixedString(x) of argument of function like #9882 **fixed via #9890**
- [x] Logical error: CROSS JOIN has expressions #9910 **fixed via #10311 in 20.3.7**
- [x] Multiple JOIN do not support asterisks for complex queries yet #10481 **fixed via #9739 in 20.4**
- [ ] Aggregate function "x" is found inside another aggregate function in query (clash of aliases) #9715
- [x] Cannot refer column "x" to table #9855 
- [x] Illegal types Float64 and Decimal(9, 2) of arguments of function multiply #9881 

Common join optimizations:
- [ ] Use right table as a predicate for the left one #8062
- [x] AND (cond OR cond) prevents CROSS JOIN to INNER JOIN rewrite #19856 **partially fixed via #20392 in 21.4**

Merge join performance optimizations:
- [ ] Adaptive bucketing of the left table
- [ ] Using PK sorting of the left table
- [ ] Using PK sorting of the right table

**Comment by leoones** [comment]
> TPC-DS compatibility issues in 20.3+.
> 
> Missing features:
> 
> * [ ]  INTERSECT / EXCEPT operators not implemented
> * [ ]  [NOT] EXISTS-operator not implemented
> * [ ]  Interval syntax like '+ 30 days' is not supported
> * [ ]  CTE syntax is different
> * [ ]  CTE returning a table is not supported
> * [ ]  Window functions are not supported
> * [ ]  RANK OVER is not supported
> * [ ]  [GROUPING](https://docs.microsoft.com/en-us/sql/t-sql/functions/grouping-transact-sql?view=sql-server-ver15) aggregate function not implemented
> 
> Bugs:
> 
> * [ ]  Illegal types Float64 and Decimal(9, 2) of arguments of function multiply #9881
> * [ ]  count(*) is not supported for multiple join queries #9853
> * [ ]  Cannot refer column "x" to table #9855
> * [ ]  Missing columns: "x" while processing query #9861
> * [x]  COMMA to CROSS JOIN rewriter is not enabled or cannot rewrite query #9863 **fixed via #9830 in 20.3.5**
> * [x]  Mix of COMMA and other JOINS is not supported #9864 **fixed via #9830 in 20.3.5**
> * [ ]  Aggregate function "x" is found inside another aggregate function in query #9715
> * [ ]  illegal type FixedString(x) of argument of function like #9882



**When can I support this**  ？？

 CTE syntax is different
 CTE returning a table is not supported
 Window functions are not supported
 RANK OVER is not supported
 GROUPING aggregate function not implemented

**Comment by 4ertus2** [comment]
> Missing columns: "x" while processing query #9861

It's an error for not implemented correlated subquery. So it's a feature too

**Comment by alex-zaitsev** [comment]
@4ertus2 , agree. Moved to features section

**Comment by leoones** [comment]
> @4ertus2 , agree. Moved to features section
really want these features ！

**Comment by leoones** [comment]
> @4ertus2 , agree. Moved to features section

Hope to add in later versions

**Comment by leoones** [comment]
> TPC-DS check list in 20.3+.
> 
> Missing features:
> 
> * [ ]  INTERSECT / EXCEPT operators not implemented
> * [ ]  [NOT] EXISTS-operator not implemented #6852
> * [ ]  Interval syntax like '+ 30 days' is not supported
> * [ ]  CTE syntax is different from ANSI SQL 99
> * [ ]  CTE returning multiple rows is not supported #2416
> * [ ]  Window  functions are not supported (OVER ... PARTITION BY ... ) #1469
> * [ ]  Missing analytical functions RANK, FIRST, LAST, LAG
> * [ ]  [GROUPING](https://docs.microsoft.com/en-us/sql/t-sql/functions/grouping-transact-sql?view=sql-server-ver15) aggregate function not implemented
> * [ ]  Correlated subqueries are not supported (Missing columns: "x" while processing query) #6697 #9861
> 
> Bugs:
> 
> * [x]  count(*) is not supported for multiple join queries #9853 **fixed via #10291 in 20.3.8**
> * [x]  COMMA to CROSS JOIN rewriter is not enabled or cannot rewrite query #9863 **fixed via #9830 in 20.3.5**
> * [x]  Mix of COMMA and other JOINS is not supported #9864 **fixed via #9830 in 20.3.5**
> * [x]  illegal type FixedString(x) of argument of function like #9882 **fixed via #9890**
> * [x]  Logical error: CROSS JOIN has expressions #9910 **fixed via #10311 in 20.3.7**
> * [x]  Multiple JOIN do not support asterisks for complex queries yet #10481 **fixed via #9739 in 20.4**
> * [ ]  Aggregate function "x" is found inside another aggregate function in query (clash of aliases) #9715
> * [ ]  Cannot refer column "x" to table #9855
> * [ ]  Illegal types Float64 and Decimal(9, 2) of arguments of function multiply #9881
> 
> Common join optimizations:
> 
> * [ ]  Use right table as a predicate for the left one #8062
> 
> Merge join performance optimizations:
> 
> * [ ]  Adaptive bucketing of the left table
> * [ ]  Using PK sorting of the left table
> * [ ]  Using PK sorting of the right table

When can the with statement return multiple lines  ？？
Window functions are not supported (OVER ... PARTITION BY ... )  &  analytical functions RANK, FIRST, LAST, LAG    ， Do you have a plan  ？？

**Comment by alex-zaitsev** [comment]
@leoones , 'WITH' returning multiple lines is hopefully for Q3 and window functions for Q4 earliest. Those are complex projects, and we are looking for contributors and sponsors to get it done.

**Comment by vkingnew** [comment]
this functions are very import to analyse complex query,desire it!
>CTE syntax is different
CTE returning a table is not supported
Window functions are not supported
RANK OVER is not supported

**Comment by ucasFL** [comment]
> Interval syntax like '+ 30 days' is not supported

This task has been done in [15978](https://github.com/ClickHouse/ClickHouse/pull/15978) @alex-zaitsev

**Comment by UnamedRus** [comment]
@ucasFL 
It's more about not using keyword INTERVAL in queries.

> Interval syntax like '+ 30 days' is not supported

```
postgres=# SELECT now() + '30 day';
           ?column?
-------------------------------
 2021-02-19 04:01:01.766836+03
(1 row)
postgres=# SELECT now() + '30 days';
           ?column?
-------------------------------
 2021-02-19 04:04:31.177359+03
(1 row)

LAPTOP-319G0GMQ.localdomain :) SELECT now() + '30 day'
Received exception from server (version 21.1.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types DateTime and String of arguments of function plus: While processing now() + '30 day'.

```

**Comment by alexey-milovidov** [comment]
INTERSECT, EXCEPT, ANY, ALL implemented by Kirill Ershov and Ksenia Sumarokova.

**Comment by alex-zaitsev** [comment]
EXISTS https://github.com/ClickHouse/ClickHouse/pull/29731

**Comment by alexey-milovidov** [comment]
GROUPING SETS have been implemented.

**Comment by UnamedRus** [comment]
@alexey-milovidov 

grouping function not implemented.

https://github.com/ClickHouse/ClickHouse/issues/19426

**Comment by alexey-milovidov** [comment]
I've updated the description.

**Comment by alexey-milovidov** [comment]
GROUPING SETS will not be available in 22.1 release.

**Comment by alexey-milovidov** [comment]
GROUPING SETS are available in 22.5.
GROUPING function is available in 22.6.
